import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const { reportId, repo, analysis, createIssuesForCritical = true } = await req.json();

    if (!reportId || !repo || !analysis) {
      return Response.json({ error: 'Missing required fields' }, { status: 400 });
    }

    const GITHUB_TOKEN = Deno.env.get('GITHUB_TOKEN');
    if (!GITHUB_TOKEN) {
      return Response.json({ error: 'GITHUB_TOKEN not configured' }, { status: 400 });
    }

    // Build issue body from analysis
    const criticalIssues = analysis.recommendations?.filter((r) => r.priority === 'critical') || [];
    const issueBody = `# QA Audit Report
URL: ${analysis.url || 'unknown'}
Score: ${analysis.scores?.overall || 'N/A'}/10
Date: ${new Date().toISOString()}

## Critical Issues (${criticalIssues.length})
${criticalIssues.map((i) => `- **${i.action}** (${i.layer})`).join('\n') || 'None'}

## Layer Scores
- UI/UX: ${analysis.scores?.ui_ux || 0}/10
- API: ${analysis.scores?.api || 0}/10
- Logic: ${analysis.scores?.logic || 0}/10
- Business Value: ${analysis.scores?.business_value || 0}/10

## Recommendations
${analysis.recommendations?.slice(0, 5).map((r) => `- [${r.priority.toUpperCase()}] ${r.action}`).join('\n') || 'None'}

---
Auto-generated by QA Audit Engine`;

    // Create GitHub issue
    const issueRes = await fetch(`https://api.github.com/repos/${repo}/issues`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${GITHUB_TOKEN}`,
        'Content-Type': 'application/json',
        'X-GitHub-Api-Version': '2022-11-28',
      },
      body: JSON.stringify({
        title: `QA Audit: ${analysis.scores?.overall || 0}/10 - ${analysis.url?.split('/')[2] || 'unknown'}`,
        body: issueBody,
        labels: ['qa-audit', `score-${Math.floor(analysis.scores?.overall || 0)}`],
      }),
    });

    if (!issueRes.ok) {
      throw new Error(`GitHub API error: ${issueRes.statusText}`);
    }

    const issue = await issueRes.json();

    // Save sync record
    const sync = await base44.entities.GitHubSync.create({
      report_id: reportId,
      github_repo: repo,
      github_issue_number: issue.number,
      issue_title: issue.title,
      issue_body: issueBody,
      labels: ['qa-audit'],
      status: 'created',
      synced_at: new Date().toISOString(),
    });

    return Response.json({ success: true, issue_number: issue.number, sync });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});