import { createHash, randomUUID } from 'node:crypto';
import {
  APPROVED_SANDBOX_OWNER,
  APPROVED_SANDBOX_REPO,
} from './runtimeDispatchAuthorityProof.js';

export const BUILD_EXECUTION_WORKER_MODULE = 'api/_lib/buildExecutionWorker.js';
export const BUILD_EXECUTION_WORKER_ENTRY_POINT = '/api/forge/build';
export const BUILD_EXECUTION_WORKER_WORKFLOW_FILE_NAME = 'flowai-build-execution-worker-stage1.yml';
export const BUILD_EXECUTION_WORKER_WORKFLOW_PATH = `.github/workflows/${BUILD_EXECUTION_WORKER_WORKFLOW_FILE_NAME}`;
export const BUILD_EXECUTION_WORKER_WORKFLOW_IDENTIFIER = BUILD_EXECUTION_WORKER_WORKFLOW_FILE_NAME;

const GITHUB_API_BASE = 'https://api.github.com';
const DEFAULT_POLL_INTERVAL_MS = 4_000;
const DEFAULT_MAX_POLL_ATTEMPTS = 60;
const SAFE_PROOF_ID = /^[a-zA-Z0-9._-]+$/;

export class BuildExecutionWorkerError extends Error {
  constructor(message, { status = 500, code = 'BUILD_EXECUTION_WORKER_ERROR', details = null } = {}) {
    super(message);
    this.name = 'BuildExecutionWorkerError';
    this.status = status;
    this.code = code;
    this.details = details;
  }
}

export function createBuildRequestId(now = new Date(), idFactory = randomUUID) {
  const stamp = now.toISOString().replace(/[-:.]/g, '').slice(0, 15);
  return `flowai-build-request-${stamp}-${idFactory().slice(0, 8)}`;
}

export function createBuildProofRunId(now = new Date(), idFactory = randomUUID) {
  const stamp = now.toISOString().replace(/[-:.]/g, '').slice(0, 15);
  return `flowai-build-${stamp}-${idFactory().slice(0, 8)}`;
}

export function resolveFlowAiBuildCommit(env = process.env) {
  return (
    env.VERCEL_GIT_COMMIT_SHA
    || env.FLOWAI_EXPECTED_HEAD
    || env.GIT_COMMIT
    || env.GIT_BRANCH
    || 'unknown'
  );
}

export function resolveBuildExecutionSandbox(env = process.env) {
  const owner = (env.FLOWAI_BUILD_EXECUTION_SANDBOX_OWNER || APPROVED_SANDBOX_OWNER).trim();
  const repo = (env.FLOWAI_BUILD_EXECUTION_SANDBOX_REPO || APPROVED_SANDBOX_REPO).trim();
  return {
    owner,
    repo,
    fullName: `${owner}/${repo}`,
    approved: owner === APPROVED_SANDBOX_OWNER && repo === APPROVED_SANDBOX_REPO,
  };
}

export function assertApprovedBuildExecutionSandbox(config) {
  if (!config?.approved) {
    throw new BuildExecutionWorkerError('BuildExecutionWorker target is not the approved sandbox repository.', {
      status: 409,
      code: 'SANDBOX_BOUNDARY_STOP',
      details: {
        requestedSandbox: config?.fullName || null,
        approvedSandbox: `${APPROVED_SANDBOX_OWNER}/${APPROVED_SANDBOX_REPO}`,
      },
    });
  }
}

export function mutatedFilePathForProofRun(proofRunId) {
  assertSafeProofRunId(proofRunId);
  return `proof/build-execution/${proofRunId}.json`;
}

export function buildExecutionWorkerWorkflowContent() {
  return [
    'name: FlowAI BuildExecutionWorker Stage 1',
    '',
    'run-name: FlowAI build execution worker stage1 ${{ inputs.proofRunId }}',
    '',
    'on:',
    '  workflow_dispatch:',
    '    inputs:',
    '      proofRunId:',
    '        description: FlowAI build proof nonce',
    '        required: true',
    '        type: string',
    '      buildRequestId:',
    '        description: FlowAI Build request id',
    '        required: true',
    '        type: string',
    '      dispatchSource:',
    '        description: Dispatch source recorded by FlowAI Build path',
    '        required: true',
    '        type: string',
    '      selectedToolId:',
    '        description: Tool Intelligence selected tool id/name',
    '        required: true',
    '        type: string',
    '      selectedMemberId:',
    '        description: Orchestra member id used for selected tool dispatch',
    '        required: true',
    '        type: string',
    '      mutationPayloadBase64:',
    '        description: Base64 JSON payload generated by FlowAI Build path',
    '        required: true',
    '        type: string',
    '      flowaiCommit:',
    '        description: FlowAI runtime commit identity',
    '        required: true',
    '        type: string',
    '',
    'permissions:',
    '  contents: write',
    '',
    'jobs:',
    '  mutate-sandbox:',
    '    name: Commit selected tool output to sandbox',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - name: Checkout sandbox',
    '        uses: actions/checkout@v4',
    '      - name: Write selected-tool output payload',
    '        shell: bash',
    '        env:',
    '          PROOF_RUN_ID: ${{ inputs.proofRunId }}',
    '          BUILD_REQUEST_ID: ${{ inputs.buildRequestId }}',
    '          MUTATION_PAYLOAD_BASE64: ${{ inputs.mutationPayloadBase64 }}',
    '        run: |',
    '          set -euo pipefail',
    '          node <<\'NODE\'',
    '          const fs = require("fs");',
    '          const path = require("path");',
    '          const proofRunId = process.env.PROOF_RUN_ID;',
    '          const buildRequestId = process.env.BUILD_REQUEST_ID;',
    '          const encoded = process.env.MUTATION_PAYLOAD_BASE64 || "";',
    '          const raw = Buffer.from(encoded, "base64").toString("utf8");',
    '          const payload = JSON.parse(raw);',
    '          if (payload.proofRunId !== proofRunId) throw new Error("proofRunId mismatch");',
    '          if (payload.buildRequestId !== buildRequestId) throw new Error("buildRequestId mismatch");',
    '          const target = `proof/build-execution/${proofRunId}.json`;',
    '          fs.mkdirSync(path.dirname(target), { recursive: true });',
    '          fs.writeFileSync(target, JSON.stringify(payload, null, 2) + "\\n");',
    '          console.log(`wrote ${target}`);',
    '          NODE',
    '      - name: Commit sandbox mutation',
    '        shell: bash',
    '        run: |',
    '          set -euo pipefail',
    '          git config user.name "FlowAI BuildExecutionWorker"',
    '          git config user.email "flowai-build-execution-worker@users.noreply.github.com"',
    '          git add "proof/build-execution/${{ inputs.proofRunId }}.json"',
    '          git commit -m "FlowAI BuildExecutionWorker Stage 1 ${{ inputs.proofRunId }}"',
    '          git push',
    '      - name: Upload mutation result',
    '        uses: actions/upload-artifact@v4',
    '        with:',
    '          name: flowai-build-execution-worker-${{ inputs.proofRunId }}',
    '          path: proof/build-execution/${{ inputs.proofRunId }}.json',
    '          if-no-files-found: error',
    '          retention-days: 1',
    '',
  ].join('\n');
}

function assertSafeProofRunId(proofRunId) {
  if (typeof proofRunId !== 'string' || !SAFE_PROOF_ID.test(proofRunId)) {
    throw new BuildExecutionWorkerError('Invalid proofRunId for sandbox mutation path.', {
      status: 400,
      code: 'INVALID_PROOF_RUN_ID',
      details: { proofRunId: typeof proofRunId === 'string' ? proofRunId.slice(0, 80) : null },
    });
  }
}

function encodeRepoPath(path) {
  return path.split('/').map(part => encodeURIComponent(part)).join('/');
}

function asBase64(text) {
  return Buffer.from(text, 'utf8').toString('base64');
}

function fromBase64(text = '') {
  return Buffer.from(String(text).replace(/\n/g, ''), 'base64').toString('utf8');
}

function sha256(text) {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

function sanitizeGitHubErrorPayload(data) {
  if (!data || typeof data !== 'object') return null;
  return {
    message: typeof data.message === 'string' ? data.message : undefined,
    documentation_url: typeof data.documentation_url === 'string' ? data.documentation_url : undefined,
    status: typeof data.status === 'string' ? data.status : undefined,
  };
}

async function githubRequest(path, {
  method = 'GET',
  body = undefined,
  token,
  fetchImpl,
}) {
  const res = await fetchImpl(`${GITHUB_API_BASE}${path}`, {
    method,
    headers: {
      Accept: 'application/vnd.github+json',
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
      'User-Agent': 'flowai-build-execution-worker',
      'X-GitHub-Api-Version': '2022-11-28',
    },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await res.text();
  let data = null;
  if (text) {
    try {
      data = JSON.parse(text);
    } catch {
      data = { raw: text.slice(0, 500) };
    }
  }
  if (!res.ok) {
    throw new BuildExecutionWorkerError(`GitHub API request failed: ${method} ${path}`, {
      status: res.status,
      code: 'GITHUB_API_FAILED',
      details: {
        status: res.status,
        path,
        method,
        response: sanitizeGitHubErrorPayload(data),
      },
    });
  }
  return { status: res.status, data, headers: res.headers };
}

async function ensureSandboxWorkflow({
  token,
  fetchImpl,
  sandbox,
  workflowContent,
}) {
  const repo = await githubRequest(`/repos/${sandbox.owner}/${sandbox.repo}`, { token, fetchImpl });
  const repoData = repo.data || {};
  const defaultBranch = repoData.default_branch || 'main';
  const permissions = repoData.permissions || {};
  if (repoData.full_name !== sandbox.fullName) {
    throw new BuildExecutionWorkerError('GitHub repository identity did not match approved sandbox.', {
      status: 409,
      code: 'SANDBOX_IDENTITY_MISMATCH',
      details: { expected: sandbox.fullName, observed: repoData.full_name || null },
    });
  }

  let existing = null;
  let existingSha = null;
  const contentPath = `/repos/${sandbox.owner}/${sandbox.repo}/contents/${encodeRepoPath(BUILD_EXECUTION_WORKER_WORKFLOW_PATH)}?ref=${encodeURIComponent(defaultBranch)}`;
  try {
    const current = await githubRequest(contentPath, { token, fetchImpl });
    existing = fromBase64(current.data?.content || '');
    existingSha = current.data?.sha || null;
  } catch (error) {
    if (!(error instanceof BuildExecutionWorkerError) || error.status !== 404) throw error;
  }

  if (existing === workflowContent) {
    return {
      status: 'UNCHANGED',
      defaultBranch,
      commitSha: null,
      permissions: {
        admin: permissions.admin === true,
        push: permissions.push === true,
      },
    };
  }

  const writeBody = {
    message: 'chore: add FlowAI BuildExecutionWorker Stage 1 workflow',
    content: asBase64(workflowContent),
    branch: defaultBranch,
  };
  if (existingSha) writeBody.sha = existingSha;

  const written = await githubRequest(`/repos/${sandbox.owner}/${sandbox.repo}/contents/${encodeRepoPath(BUILD_EXECUTION_WORKER_WORKFLOW_PATH)}`, {
    method: 'PUT',
    body: writeBody,
    token,
    fetchImpl,
  });

  return {
    status: existingSha ? 'UPDATED' : 'CREATED',
    defaultBranch,
    commitSha: written.data?.commit?.sha || null,
    permissions: {
      admin: permissions.admin === true,
      push: permissions.push === true,
    },
  };
}

async function waitForWorkflow({ token, fetchImpl, sandbox, sleepImpl, pollIntervalMs, maxAttempts }) {
  let lastError = null;
  for (let attempt = 0; attempt < maxAttempts; attempt += 1) {
    try {
      const workflow = await githubRequest(`/repos/${sandbox.owner}/${sandbox.repo}/actions/workflows/${encodeURIComponent(BUILD_EXECUTION_WORKER_WORKFLOW_IDENTIFIER)}`, {
        token,
        fetchImpl,
      });
      return {
        id: workflow.data?.id || null,
        name: workflow.data?.name || null,
        path: workflow.data?.path || BUILD_EXECUTION_WORKER_WORKFLOW_PATH,
        state: workflow.data?.state || null,
      };
    } catch (error) {
      lastError = error;
      if (!(error instanceof BuildExecutionWorkerError) || error.status !== 404) throw error;
      await sleepImpl(pollIntervalMs);
    }
  }
  throw new BuildExecutionWorkerError('BuildExecutionWorker workflow was not discoverable after creation.', {
    status: 409,
    code: 'WORKFLOW_DISCOVERY_BLOCK',
    details: lastError?.details || null,
  });
}

function runMatchesProofId(run, proofRunId, dispatchedAtMs) {
  const displayTitle = run?.display_title || '';
  const name = run?.name || '';
  const createdAtMs = Date.parse(run?.created_at || '');
  return (
    Number.isFinite(createdAtMs)
    && createdAtMs >= dispatchedAtMs - 30_000
    && (displayTitle.includes(proofRunId) || name.includes(proofRunId))
  );
}

async function waitForRun({
  token,
  fetchImpl,
  sandbox,
  proofRunId,
  dispatchedAtMs,
  sleepImpl,
  pollIntervalMs,
  maxAttempts,
}) {
  let matched = null;
  for (let attempt = 0; attempt < maxAttempts; attempt += 1) {
    const runs = await githubRequest(
      `/repos/${sandbox.owner}/${sandbox.repo}/actions/workflows/${encodeURIComponent(BUILD_EXECUTION_WORKER_WORKFLOW_IDENTIFIER)}/runs?event=workflow_dispatch&per_page=20`,
      { token, fetchImpl },
    );
    matched = (runs.data?.workflow_runs || []).find(run => runMatchesProofId(run, proofRunId, dispatchedAtMs)) || matched;
    if (matched?.id && matched.status === 'completed') return matched;
    await sleepImpl(pollIntervalMs);
  }
  if (matched?.id) return matched;
  throw new BuildExecutionWorkerError('No sandbox workflow run matched the BuildExecutionWorker proofRunId.', {
    status: 409,
    code: 'RUN_DISCOVERY_BLOCK',
    details: { proofRunId },
  });
}

async function listRunArtifacts({ token, fetchImpl, sandbox, runId }) {
  const artifacts = await githubRequest(`/repos/${sandbox.owner}/${sandbox.repo}/actions/runs/${runId}/artifacts?per_page=30`, {
    token,
    fetchImpl,
  });
  return artifacts.data?.artifacts || [];
}

async function readSandboxMutationCommit({
  token,
  fetchImpl,
  sandbox,
  defaultBranch,
  proofRunId,
  mutatedFilePath,
  sleepImpl,
  pollIntervalMs,
  maxAttempts,
}) {
  let lastError = null;
  for (let attempt = 0; attempt < maxAttempts; attempt += 1) {
    try {
      const commits = await githubRequest(
        `/repos/${sandbox.owner}/${sandbox.repo}/commits?path=${encodeURIComponent(mutatedFilePath)}&sha=${encodeURIComponent(defaultBranch)}&per_page=10`,
        { token, fetchImpl },
      );
      const commit = (commits.data || []).find(item => (item.commit?.message || '').includes(proofRunId));
      if (commit?.sha) {
        const content = await githubRequest(
          `/repos/${sandbox.owner}/${sandbox.repo}/contents/${encodeRepoPath(mutatedFilePath)}?ref=${encodeURIComponent(commit.sha)}`,
          { token, fetchImpl },
        );
        const decoded = fromBase64(content.data?.content || '');
        let parsed = null;
        try {
          parsed = JSON.parse(decoded);
        } catch {
          parsed = null;
        }
        if (parsed?.proofRunId === proofRunId) {
          return {
            commitSha: commit.sha,
            commitHtmlUrl: commit.html_url || null,
            contentSha: content.data?.sha || null,
            parsed,
          };
        }
      }
    } catch (error) {
      lastError = error;
      if (!(error instanceof BuildExecutionWorkerError) || error.status !== 404) throw error;
    }
    await sleepImpl(pollIntervalMs);
  }
  throw new BuildExecutionWorkerError('No sandbox commit matched the BuildExecutionWorker proofRunId.', {
    status: 409,
    code: 'SANDBOX_COMMIT_DISCOVERY_BLOCK',
    details: {
      proofRunId,
      mutatedFilePath,
      lastError: lastError?.details || null,
    },
  });
}

function selectedToolLabel(selectedTool) {
  return selectedTool?.toolId
    || selectedTool?.id
    || selectedTool?.platform_name
    || selectedTool?.toolName
    || selectedTool?.name
    || 'unknown';
}

function createMutationPayload({
  proofRunId,
  buildRequestId,
  productId,
  runId,
  targetFilePath,
  selectedTool,
  selectedMemberId,
  dispatchResult,
  selectedToolOutput,
  sandbox,
  flowaiCommit,
  now,
}) {
  const output = typeof selectedToolOutput === 'string'
    ? selectedToolOutput
    : JSON.stringify(selectedToolOutput ?? null);
  if (typeof output !== 'string' || output.trim().length === 0) {
    throw new BuildExecutionWorkerError('Selected tool output is required for sandbox mutation.', {
      status: 409,
      code: 'SELECTED_TOOL_OUTPUT_MISSING',
    });
  }

  return {
    proofRunId,
    buildRequestId,
    productId: productId ?? null,
    runId: runId ?? null,
    flowaiCommit,
    selectedTool: selectedTool ? { ...selectedTool } : null,
    selectedToolId: selectedToolLabel(selectedTool),
    selectedMemberId,
    dispatch: {
      action: dispatchResult?.action ?? null,
      member: dispatchResult?.member ?? null,
      model: dispatchResult?.data?.model ?? null,
      usage: dispatchResult?.data?.usage ?? null,
      filePath: dispatchResult?.data?.filePath ?? targetFilePath ?? null,
    },
    targetFilePath,
    selectedToolOutput: output,
    selectedToolOutputSha256: sha256(output),
    sandbox: {
      owner: sandbox.owner,
      repo: sandbox.repo,
      fullName: sandbox.fullName,
      approved: sandbox.approved,
    },
    createdAt: now.toISOString(),
    claimBoundary: 'BUILD-PATH DISPATCH DEMONSTRATED candidate evidence only; no deploy, persistence, or behavior proof',
  };
}

export async function runBuildExecutionWorkerMutation({
  proofRunId,
  buildRequestId,
  productId = null,
  runId = null,
  targetFilePath,
  selectedTool,
  selectedMemberId,
  dispatchResult,
  selectedToolOutput,
  env = process.env,
  fetchImpl = globalThis.fetch,
  now = () => new Date(),
  sleepImpl = sleep,
  pollIntervalMs = DEFAULT_POLL_INTERVAL_MS,
  maxPollAttempts = DEFAULT_MAX_POLL_ATTEMPTS,
} = {}) {
  if (typeof fetchImpl !== 'function') {
    throw new BuildExecutionWorkerError('fetch implementation is unavailable.', {
      status: 500,
      code: 'FETCH_UNAVAILABLE',
    });
  }
  assertSafeProofRunId(proofRunId);
  if (typeof buildRequestId !== 'string' || buildRequestId.trim().length === 0) {
    throw new BuildExecutionWorkerError('buildRequestId is required for BuildExecutionWorker mutation.', {
      status: 400,
      code: 'BUILD_REQUEST_ID_MISSING',
    });
  }
  if (typeof selectedMemberId !== 'string' || selectedMemberId.trim().length === 0) {
    throw new BuildExecutionWorkerError('selectedMemberId is required for BuildExecutionWorker mutation.', {
      status: 400,
      code: 'SELECTED_MEMBER_ID_MISSING',
    });
  }

  const token = env.GITHUB_WORKFLOW_TOKEN || env.GITHUB_OPERATOR_TOKEN || env.GITHUB_PAT;
  if (!token) {
    throw new BuildExecutionWorkerError('Workflow dispatch credential is not configured.', {
      status: 503,
      code: 'WORKFLOW_CREDENTIAL_MISSING',
    });
  }

  const sandbox = resolveBuildExecutionSandbox(env);
  assertApprovedBuildExecutionSandbox(sandbox);

  const startedAt = now();
  const flowaiCommit = resolveFlowAiBuildCommit(env);
  const mutatedFilePath = mutatedFilePathForProofRun(proofRunId);
  const mutationPayload = createMutationPayload({
    proofRunId,
    buildRequestId,
    productId,
    runId,
    targetFilePath,
    selectedTool,
    selectedMemberId,
    dispatchResult,
    selectedToolOutput,
    sandbox,
    flowaiCommit,
    now: startedAt,
  });

  const workflowWrite = await ensureSandboxWorkflow({
    token,
    fetchImpl,
    sandbox,
    workflowContent: buildExecutionWorkerWorkflowContent(),
  });
  const workflow = await waitForWorkflow({
    token,
    fetchImpl,
    sandbox,
    sleepImpl,
    pollIntervalMs,
    maxAttempts: 6,
  });

  const dispatchedAt = now();
  const dispatchedAtMs = dispatchedAt.getTime();
  const dispatchInputs = {
    proofRunId,
    buildRequestId,
    dispatchSource: 'FlowAI Build path',
    selectedToolId: mutationPayload.selectedToolId,
    selectedMemberId,
    mutationPayloadBase64: asBase64(JSON.stringify(mutationPayload)),
    flowaiCommit,
  };

  await githubRequest(`/repos/${sandbox.owner}/${sandbox.repo}/actions/workflows/${encodeURIComponent(BUILD_EXECUTION_WORKER_WORKFLOW_IDENTIFIER)}/dispatches`, {
    method: 'POST',
    body: {
      ref: workflowWrite.defaultBranch,
      inputs: dispatchInputs,
    },
    token,
    fetchImpl,
  });

  const run = await waitForRun({
    token,
    fetchImpl,
    sandbox,
    proofRunId,
    dispatchedAtMs,
    sleepImpl,
    pollIntervalMs,
    maxAttempts: maxPollAttempts,
  });
  const artifacts = run?.id
    ? await listRunArtifacts({ token, fetchImpl, sandbox, runId: run.id })
    : [];
  const expectedArtifactName = `flowai-build-execution-worker-${proofRunId}`;
  const artifact = artifacts.find(item => item.name === expectedArtifactName) || null;
  const commitReadBack = run?.conclusion === 'success'
    ? await readSandboxMutationCommit({
      token,
      fetchImpl,
      sandbox,
      defaultBranch: workflowWrite.defaultBranch,
      proofRunId,
      mutatedFilePath,
      sleepImpl,
      pollIntervalMs,
      maxAttempts: maxPollAttempts,
    })
    : null;
  const succeeded = run.status === 'completed'
    && run.conclusion === 'success'
    && artifact?.name === expectedArtifactName
    && commitReadBack?.parsed?.proofRunId === proofRunId;

  return {
    ok: succeeded,
    status: succeeded ? 'SUCCESS' : 'BLOCK',
    module: BUILD_EXECUTION_WORKER_MODULE,
    entryPoint: BUILD_EXECUTION_WORKER_ENTRY_POINT,
    dispatchSource: 'FlowAI Build path',
    proofRunId,
    buildRequestId,
    selectedTool: {
      id: mutationPayload.selectedToolId,
      memberId: selectedMemberId,
    },
    sandbox: {
      owner: sandbox.owner,
      repo: sandbox.repo,
      fullName: sandbox.fullName,
      approved: sandbox.approved,
      permissions: workflowWrite.permissions,
      contained: sandbox.approved,
      boundary: 'approved sandbox repository only',
    },
    workflow: {
      identifier: BUILD_EXECUTION_WORKER_WORKFLOW_IDENTIFIER,
      file: BUILD_EXECUTION_WORKER_WORKFLOW_FILE_NAME,
      path: BUILD_EXECUTION_WORKER_WORKFLOW_PATH,
      id: workflow.id,
      state: workflow.state,
      writeStatus: workflowWrite.status,
      workflowCommitSha: workflowWrite.commitSha,
      defaultBranch: workflowWrite.defaultBranch,
    },
    run: run?.id ? {
      id: run.id,
      url: run.url,
      htmlUrl: run.html_url,
      event: run.event,
      actor: run.actor?.login || null,
      status: run.status,
      conclusion: run.conclusion,
      displayTitle: run.display_title || null,
      createdAt: run.created_at,
      updatedAt: run.updated_at,
    } : null,
    mutatedFilePath,
    commitSha: commitReadBack?.commitSha || null,
    commitHtmlUrl: commitReadBack?.commitHtmlUrl || null,
    contentSha: commitReadBack?.contentSha || null,
    artifact: {
      name: artifact?.name || null,
      id: artifact?.id || null,
      expectedName: expectedArtifactName,
    },
    proofRunIdContinuity: {
      buildRequest: true,
      selectedToolDispatch: dispatchResult?.member === selectedMemberId,
      runnerDispatch: dispatchInputs.proofRunId === proofRunId,
      runnerRunTitle: (run.display_title || '').includes(proofRunId),
      runnerArtifact: artifact?.name === expectedArtifactName,
      mutatedFile: commitReadBack?.parsed?.proofRunId === proofRunId,
      commitMessage: Boolean(commitReadBack?.commitSha),
      response: true,
    },
    readBack: commitReadBack ? {
      proofRunId: commitReadBack.parsed.proofRunId,
      buildRequestId: commitReadBack.parsed.buildRequestId,
      selectedToolId: commitReadBack.parsed.selectedToolId,
      selectedMemberId: commitReadBack.parsed.selectedMemberId,
      selectedToolOutputSha256: commitReadBack.parsed.selectedToolOutputSha256,
    } : null,
    containment: {
      productionDeployTouched: false,
      productionRepoMutated: false,
      customerRepoMutated: false,
      flowaiProductRepoMutated: false,
      sandboxOnly: sandbox.approved,
    },
    claimBoundary: {
      maximumClaim: succeeded
        ? 'BUILD-PATH DISPATCH DEMONSTRATED; BuildExecutionWorker Stage 1 Complete'
        : 'No BuildExecutionWorker claim moves',
      excludedClaims: [
        'BUILD_EXECUTION_VERIFIED',
        'CREATOR_VERIFIED',
        'UPGRADER_VERIFIED',
        'UNIVERSAL_ENGINE_VERIFIED',
        'Production autonomous execution',
        'Deploy proven',
        'Persistence proven',
        'Behavioral verification proven',
      ],
    },
    timestamps: {
      startedAt: startedAt.toISOString(),
      dispatchedAt: dispatchedAt.toISOString(),
      completedAt: run?.updated_at || null,
    },
  };
}

export function statusCodeForBuildExecutionWorkerResult(result) {
  if (result?.ok) return 200;
  if (result?.status === 'STOP') return 409;
  return 502;
}
