// Tool Intelligence Marketplace — taxonomy + canonical tool seed.
//
// This is the single source of truth for the marketplace's static data.
// When DB_BACKEND=supabase activates, this same shape gets pushed via
// /api/admin/seed-marketplace into the tool_categories + tools tables.
//
// Schema mirrors /supabase/migrations/0004_tool_marketplace.sql.
//
// Adding a tool: append to TOOLS. Update one place.
//
// Seed values for region_strengths + integration_complexity + vendor health
// are best-effort baselines. Fields marked in `needs_verification` should
// be cross-checked against the vendor's public docs before commercial use.

// ─── Categories ────────────────────────────────────────────────────────
//
// step_numbers: which of the 8 lifecycle steps this category serves.
//   1=Research 2=Design 3=Build 4=Quality Audit 5=Deploy
//   6=Self-Renewal 7=Go To Market 8=Monitor

export const TOOL_CATEGORIES = [
  { id: 'hosting',           name: 'Hosting & Deployment',          step_numbers: [3, 5],          display_order: 10,
    description: 'Where the application runs in production. Includes serverless platforms, edge networks, and PaaS.' },
  { id: 'databases',         name: 'Databases',                     step_numbers: [3, 5],          display_order: 20,
    description: 'Persistent data storage. Relational (Postgres-flavoured), document, and edge-resident options.' },
  { id: 'auth',              name: 'Authentication',                step_numbers: [3],             display_order: 30,
    description: 'User identity, session management, SSO, and organisation handling.' },
  { id: 'payments',          name: 'Payments',                      step_numbers: [3, 7],          display_order: 40,
    description: 'Card processing, subscriptions, billing, payouts. Region-sensitive.' },
  { id: 'email',             name: 'Email & Notifications',         step_numbers: [3, 6, 7],       display_order: 50,
    description: 'Transactional + marketing email, SMS, push notifications.' },
  { id: 'ai_llm',            name: 'AI Models — LLMs',              step_numbers: [1, 2, 3, 4, 6], display_order: 60,
    description: 'Frontier text generation models for research, drafting, summarisation, agent workflows.' },
  { id: 'ai_embeddings',     name: 'AI Models — Embeddings',        step_numbers: [1, 4],          display_order: 70,
    description: 'Vector embedding APIs for semantic search and clustering.' },
  { id: 'ai_specialized',    name: 'AI Models — Specialized',       step_numbers: [1, 2, 3, 4],    display_order: 80,
    description: 'Purpose-built APIs: web search/research (Perplexity), voice (ElevenLabs), image/video (Replicate), browser automation (Browserless).' },
  { id: 'jobs',              name: 'Background Jobs & Queues',      step_numbers: [3, 6, 8],       display_order: 90,
    description: 'Async job execution, cron, durable workflows, queues.' },
  { id: 'observability',     name: 'Observability & Logging',       step_numbers: [4, 6, 8],       display_order: 100,
    description: 'Structured logs, traces, error tracking, uptime monitoring.' },
  { id: 'analytics',         name: 'Analytics & Product Intel',     step_numbers: [7, 8],          display_order: 110,
    description: 'Usage analytics, funnel tracking, session replay, customer behavior analysis.' },
  { id: 'storage',           name: 'Storage & CDN',                 step_numbers: [3, 5],          display_order: 120,
    description: 'Object storage, asset CDN, image optimization.' },
  { id: 'gtm',               name: 'GTM & Marketing Tools',         step_numbers: [7],             display_order: 130,
    description: 'Scheduling, lifecycle marketing, roadmap management, no-code landing pages.' },
];

// ─── Tools ─────────────────────────────────────────────────────────────
//
// Region scores: 0-100. Higher = stronger fit for that region (latency,
// data residency, payment-rail availability, language support, support
// hours overlap).
//
// integration_complexity: 1=trivial drop-in SDK, 5=expert-only.
// data_export_ease: 'trivial'|'moderate'|'difficult'|'impossible'.
// last_funding_round: 'pre-seed'|'seed'|'series-a'..'series-f'|'public'|'profitable_bootstrapped'|'unknown'.

const RX = (africa, europe, us, asia, latam) => ({ africa, europe, us, asia, latam });

export const TOOLS = [
  // ─── HOSTING ─────────────────────────────────────────────────────────
  { slug: 'vercel', category_id: 'hosting', name: 'Vercel', vendor: 'Vercel Inc.',
    description: 'Edge-first deployment platform optimised for Next.js + frontend frameworks. Best-in-class DX for JavaScript stacks.',
    homepage_url: 'https://vercel.com', pricing_url: 'https://vercel.com/pricing',
    pricing_model: 'free_tier+usage', has_free_tier: true, free_tier_summary: 'Hobby tier: 1 user, 100GB bandwidth, 100K function invocations',
    starting_paid_tier_usd: 20, pricing_unit: 'per seat + usage',
    region_strengths: RX(60, 88, 95, 80, 70), data_residency_options: ['us-east','us-west','eu-west','ap-south'],
    compliance_certs: ['SOC2','ISO27001','HIPAA','GDPR'], integration_complexity: 1, setup_time_estimate_minutes: 5,
    primary_languages: ['javascript','typescript','python','go'],
    last_funding_round: 'series-d', last_funding_year: 2021, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'netlify', category_id: 'hosting', name: 'Netlify', vendor: 'Netlify',
    description: 'Frontend deployment platform. Strong build pipeline, edge functions, forms-as-a-service.',
    homepage_url: 'https://netlify.com', pricing_url: 'https://www.netlify.com/pricing/',
    pricing_model: 'free_tier+usage', has_free_tier: true, starting_paid_tier_usd: 19,
    region_strengths: RX(55, 82, 90, 78, 65), data_residency_options: ['us-east','eu-west'],
    compliance_certs: ['SOC2','GDPR'], integration_complexity: 1, setup_time_estimate_minutes: 5,
    primary_languages: ['javascript','typescript'],
    last_funding_round: 'series-d', last_funding_year: 2021, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'cloudflare-pages', category_id: 'hosting', name: 'Cloudflare Pages', vendor: 'Cloudflare',
    description: 'Static + serverless deployments on the Cloudflare edge. Excellent global latency, generous free tier.',
    homepage_url: 'https://pages.cloudflare.com', pricing_url: 'https://www.cloudflare.com/plans/',
    pricing_model: 'free_tier+usage', has_free_tier: true, starting_paid_tier_usd: 5,
    region_strengths: RX(85, 95, 95, 90, 85), data_residency_options: ['global-edge','us-east','eu-west'],
    compliance_certs: ['SOC2','ISO27001','HIPAA','GDPR','PCI'], integration_complexity: 2, setup_time_estimate_minutes: 10,
    primary_languages: ['javascript','typescript','rust','python'],
    last_funding_round: 'public', last_funding_year: 2019, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'railway', category_id: 'hosting', name: 'Railway', vendor: 'Railway',
    description: 'PaaS for full-stack apps with Postgres + Redis + workers. Simpler than AWS, more flexible than Vercel.',
    homepage_url: 'https://railway.app', pricing_url: 'https://railway.app/pricing',
    pricing_model: 'usage_only', has_free_tier: true, free_tier_summary: 'Trial $5 free credit; usage-based after',
    starting_paid_tier_usd: 5, pricing_unit: 'usage credits',
    region_strengths: RX(50, 80, 92, 75, 60), data_residency_options: ['us-west','eu-west','ap-southeast'],
    compliance_certs: ['SOC2'], integration_complexity: 2, setup_time_estimate_minutes: 15,
    primary_languages: ['javascript','typescript','python','go','ruby','rust','php'],
    last_funding_round: 'series-a', last_funding_year: 2024, public_incident_frequency: 'medium',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'render', category_id: 'hosting', name: 'Render', vendor: 'Render',
    description: 'Heroku-style PaaS with predictable pricing. Web services, cron, Postgres, Redis.',
    homepage_url: 'https://render.com', pricing_url: 'https://render.com/pricing',
    pricing_model: 'subscription', has_free_tier: true, starting_paid_tier_usd: 7,
    region_strengths: RX(50, 80, 90, 75, 60), data_residency_options: ['us-east','us-west','eu-west','ap-southeast'],
    compliance_certs: ['SOC2','GDPR','HIPAA'], integration_complexity: 2, setup_time_estimate_minutes: 15,
    primary_languages: ['javascript','typescript','python','go','ruby','rust','php','elixir'],
    last_funding_round: 'series-b', last_funding_year: 2022, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'fly-io', category_id: 'hosting', name: 'Fly.io', vendor: 'Fly.io',
    description: 'Run full-stack apps on a global edge network with Postgres and persistent volumes.',
    homepage_url: 'https://fly.io', pricing_url: 'https://fly.io/docs/about/pricing/',
    pricing_model: 'usage_only', has_free_tier: false, starting_paid_tier_usd: 5,
    region_strengths: RX(70, 88, 90, 82, 70), data_residency_options: ['30+ regions globally'],
    compliance_certs: ['SOC2'], integration_complexity: 3, setup_time_estimate_minutes: 30,
    primary_languages: ['javascript','typescript','python','go','elixir','ruby','rust'],
    last_funding_round: 'series-b', last_funding_year: 2022, public_incident_frequency: 'medium',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'aws-amplify', category_id: 'hosting', name: 'AWS Amplify', vendor: 'AWS',
    description: 'Full-stack platform from AWS. Best when you need deep AWS integration; heavy.',
    homepage_url: 'https://aws.amazon.com/amplify/', pricing_url: 'https://aws.amazon.com/amplify/pricing/',
    pricing_model: 'usage_only', has_free_tier: true, starting_paid_tier_usd: 0,
    region_strengths: RX(75, 90, 95, 90, 75), data_residency_options: ['30+ AWS regions'],
    compliance_certs: ['SOC2','ISO27001','HIPAA','GDPR','PCI','FedRAMP'], integration_complexity: 4, setup_time_estimate_minutes: 60,
    primary_languages: ['javascript','typescript','swift','kotlin'],
    last_funding_round: 'public', last_funding_year: 2006, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'difficult' },

  // ─── DATABASES ───────────────────────────────────────────────────────
  { slug: 'supabase', category_id: 'databases', name: 'Supabase', vendor: 'Supabase',
    description: 'Postgres + auth + storage + realtime + edge functions. Open-source Firebase alternative.',
    homepage_url: 'https://supabase.com', pricing_url: 'https://supabase.com/pricing',
    pricing_model: 'free_tier+usage', has_free_tier: true, free_tier_summary: '500MB DB, 50K MAU, 5GB bandwidth',
    starting_paid_tier_usd: 25, pricing_unit: 'per project + usage',
    region_strengths: RX(70, 88, 92, 80, 75), data_residency_options: ['us-east','eu-west','ap-southeast','sa-east','ap-south'],
    compliance_certs: ['SOC2','HIPAA','GDPR'], integration_complexity: 1, setup_time_estimate_minutes: 10,
    primary_languages: ['javascript','typescript','python','swift','kotlin','dart','rust'],
    last_funding_round: 'series-c', last_funding_year: 2024, public_incident_frequency: 'low',
    open_source: true, self_hostable: true, data_export_ease: 'trivial' },
  { slug: 'planetscale', category_id: 'databases', name: 'PlanetScale', vendor: 'PlanetScale',
    description: 'Serverless MySQL with branching, deploy requests, and online schema changes.',
    homepage_url: 'https://planetscale.com', pricing_url: 'https://planetscale.com/pricing',
    pricing_model: 'subscription', has_free_tier: false, starting_paid_tier_usd: 39,
    region_strengths: RX(60, 85, 92, 82, 70), data_residency_options: ['us-east','us-west','eu-west','eu-central','ap-southeast','ap-northeast','sa-east'],
    compliance_certs: ['SOC2','HIPAA','GDPR'], integration_complexity: 2, setup_time_estimate_minutes: 15,
    primary_languages: ['any (MySQL wire protocol)'],
    last_funding_round: 'series-c', last_funding_year: 2021, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'trivial' },
  { slug: 'neon', category_id: 'databases', name: 'Neon', vendor: 'Neon',
    description: 'Serverless Postgres with branching, autoscaling, and bottomless storage.',
    homepage_url: 'https://neon.tech', pricing_url: 'https://neon.tech/pricing',
    pricing_model: 'free_tier+usage', has_free_tier: true, free_tier_summary: '0.5 GB storage, 191.9 compute hours',
    starting_paid_tier_usd: 19, pricing_unit: 'per project + usage',
    region_strengths: RX(60, 85, 90, 80, 70), data_residency_options: ['us-east','us-west','eu-central','ap-southeast'],
    compliance_certs: ['SOC2','HIPAA','GDPR'], integration_complexity: 1, setup_time_estimate_minutes: 10,
    primary_languages: ['any (Postgres wire protocol)'],
    last_funding_round: 'series-c', last_funding_year: 2024, public_incident_frequency: 'low',
    open_source: true, self_hostable: true, data_export_ease: 'trivial' },
  { slug: 'mongodb-atlas', category_id: 'databases', name: 'MongoDB Atlas', vendor: 'MongoDB',
    description: 'Managed MongoDB with global clusters, vector search, and full-text search.',
    homepage_url: 'https://www.mongodb.com/atlas', pricing_url: 'https://www.mongodb.com/pricing',
    pricing_model: 'free_tier+usage', has_free_tier: true, starting_paid_tier_usd: 9,
    region_strengths: RX(70, 88, 92, 88, 75), data_residency_options: ['80+ regions across AWS/GCP/Azure'],
    compliance_certs: ['SOC2','ISO27001','HIPAA','GDPR','PCI','FedRAMP'], integration_complexity: 2, setup_time_estimate_minutes: 20,
    primary_languages: ['javascript','python','java','go','c#','ruby'],
    last_funding_round: 'public', last_funding_year: 2017, public_incident_frequency: 'low',
    open_source: true, self_hostable: true, data_export_ease: 'trivial' },
  { slug: 'firebase', category_id: 'databases', name: 'Firebase Firestore', vendor: 'Google',
    description: 'Realtime NoSQL document database with strong mobile SDKs. Pairs with Firebase Auth.',
    homepage_url: 'https://firebase.google.com/products/firestore', pricing_url: 'https://firebase.google.com/pricing',
    pricing_model: 'free_tier+usage', has_free_tier: true, starting_paid_tier_usd: 0,
    region_strengths: RX(70, 90, 95, 90, 78), data_residency_options: ['multi-region','us-central','eu-west','ap-northeast'],
    compliance_certs: ['SOC2','ISO27001','HIPAA','GDPR'], integration_complexity: 2, setup_time_estimate_minutes: 15,
    primary_languages: ['javascript','typescript','swift','kotlin','dart','python','java','go','c#'],
    last_funding_round: 'public', last_funding_year: 2004, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'difficult' },
  { slug: 'turso', category_id: 'databases', name: 'Turso', vendor: 'Turso',
    description: 'Edge-resident SQLite (libSQL) with embedded replicas. Sub-millisecond reads near users.',
    homepage_url: 'https://turso.tech', pricing_url: 'https://turso.tech/pricing',
    pricing_model: 'free_tier+usage', has_free_tier: true, starting_paid_tier_usd: 29,
    region_strengths: RX(80, 90, 92, 88, 80), data_residency_options: ['30+ edge locations'],
    compliance_certs: ['SOC2'], integration_complexity: 2, setup_time_estimate_minutes: 15,
    primary_languages: ['javascript','typescript','python','go','rust','swift'],
    last_funding_round: 'seed', last_funding_year: 2024, public_incident_frequency: 'medium',
    open_source: true, self_hostable: true, data_export_ease: 'trivial' },
  { slug: 'pocketbase', category_id: 'databases', name: 'PocketBase', vendor: 'PocketBase',
    description: 'Open-source Go-based backend in a single executable. SQLite + auth + admin UI + realtime.',
    homepage_url: 'https://pocketbase.io', pricing_url: 'https://pocketbase.io',
    pricing_model: 'open_source_self_host', has_free_tier: true, starting_paid_tier_usd: 0,
    region_strengths: RX(75, 80, 80, 80, 75), data_residency_options: ['wherever you self-host'],
    compliance_certs: [], integration_complexity: 2, setup_time_estimate_minutes: 30,
    primary_languages: ['javascript','typescript','dart','go'],
    last_funding_round: 'unknown', public_incident_frequency: 'unknown',
    open_source: true, self_hostable: true, data_export_ease: 'trivial' },

  // ─── AUTHENTICATION ──────────────────────────────────────────────────
  { slug: 'clerk', category_id: 'auth', name: 'Clerk', vendor: 'Clerk',
    description: 'Pre-built auth UIs + organisations + B2B features. Best DX for React/Next.js.',
    homepage_url: 'https://clerk.com', pricing_url: 'https://clerk.com/pricing',
    pricing_model: 'free_tier+usage', has_free_tier: true, free_tier_summary: '10K MAU free',
    starting_paid_tier_usd: 25, pricing_unit: 'per MAU above free tier',
    region_strengths: RX(60, 85, 92, 80, 70), data_residency_options: ['us','eu'],
    compliance_certs: ['SOC2','HIPAA','GDPR'], integration_complexity: 1, setup_time_estimate_minutes: 15,
    primary_languages: ['javascript','typescript','swift','kotlin','dart','python','go'],
    last_funding_round: 'series-b', last_funding_year: 2024, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'auth0', category_id: 'auth', name: 'Auth0', vendor: 'Okta',
    description: 'Enterprise identity platform with the deepest SSO + compliance feature set. Heavy.',
    homepage_url: 'https://auth0.com', pricing_url: 'https://auth0.com/pricing',
    pricing_model: 'subscription', has_free_tier: true, free_tier_summary: '7.5K MAU free',
    starting_paid_tier_usd: 35,
    region_strengths: RX(70, 92, 95, 90, 75), data_residency_options: ['us','eu','au'],
    compliance_certs: ['SOC2','ISO27001','HIPAA','GDPR','PCI','FedRAMP'], integration_complexity: 3, setup_time_estimate_minutes: 60,
    primary_languages: ['javascript','typescript','python','java','c#','go','ruby','swift','kotlin'],
    last_funding_round: 'public', last_funding_year: 2017, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'supabase-auth', category_id: 'auth', name: 'Supabase Auth', vendor: 'Supabase',
    description: 'Auth bundled with Supabase Postgres. Email, OAuth, magic-link, MFA, RLS-integrated.',
    homepage_url: 'https://supabase.com/auth', pricing_url: 'https://supabase.com/pricing',
    pricing_model: 'free_tier+usage', has_free_tier: true, starting_paid_tier_usd: 25,
    region_strengths: RX(70, 88, 92, 80, 75), data_residency_options: ['us-east','eu-west','ap-southeast','sa-east','ap-south'],
    compliance_certs: ['SOC2','HIPAA','GDPR'], integration_complexity: 1, setup_time_estimate_minutes: 15,
    primary_languages: ['javascript','typescript','python','swift','kotlin','dart'],
    last_funding_round: 'series-c', last_funding_year: 2024, public_incident_frequency: 'low',
    open_source: true, self_hostable: true, data_export_ease: 'trivial' },
  { slug: 'firebase-auth', category_id: 'auth', name: 'Firebase Auth', vendor: 'Google',
    description: 'Google-backed auth with deep mobile SDKs. Tight Firebase ecosystem coupling.',
    homepage_url: 'https://firebase.google.com/products/auth', pricing_url: 'https://firebase.google.com/pricing',
    pricing_model: 'free_tier+usage', has_free_tier: true, starting_paid_tier_usd: 0,
    region_strengths: RX(72, 88, 95, 90, 78), data_residency_options: ['multi-region'],
    compliance_certs: ['SOC2','ISO27001','HIPAA','GDPR'], integration_complexity: 2, setup_time_estimate_minutes: 20,
    primary_languages: ['javascript','swift','kotlin','dart','python'],
    last_funding_round: 'public', last_funding_year: 2004, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'difficult' },
  { slug: 'nextauth', category_id: 'auth', name: 'Auth.js (NextAuth)', vendor: 'Auth.js',
    description: 'Open-source auth library for Next.js + other frameworks. Bring-your-own database.',
    homepage_url: 'https://authjs.dev', pricing_model: 'open_source_self_host', has_free_tier: true, starting_paid_tier_usd: 0,
    region_strengths: RX(75, 80, 80, 80, 75), data_residency_options: ['wherever your DB is'],
    compliance_certs: [], integration_complexity: 3, setup_time_estimate_minutes: 45,
    primary_languages: ['javascript','typescript'],
    last_funding_round: 'unknown', public_incident_frequency: 'unknown',
    open_source: true, self_hostable: true, data_export_ease: 'trivial' },
  { slug: 'workos', category_id: 'auth', name: 'WorkOS', vendor: 'WorkOS',
    description: 'Enterprise SSO + SCIM + audit logs as a service. Pair with another auth for B2C.',
    homepage_url: 'https://workos.com', pricing_url: 'https://workos.com/pricing',
    pricing_model: 'usage_only', has_free_tier: true, free_tier_summary: '1M MAU free for AuthKit',
    starting_paid_tier_usd: 0, pricing_unit: 'per SSO connection',
    region_strengths: RX(60, 88, 95, 80, 70), data_residency_options: ['us','eu'],
    compliance_certs: ['SOC2','ISO27001','HIPAA','GDPR'], integration_complexity: 2, setup_time_estimate_minutes: 30,
    primary_languages: ['javascript','typescript','python','ruby','go','java','c#'],
    last_funding_round: 'series-b', last_funding_year: 2024, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'stytch', category_id: 'auth', name: 'Stytch', vendor: 'Stytch',
    description: 'Passwordless-first auth (magic links, SMS OTP, biometrics). Strong B2B suite.',
    homepage_url: 'https://stytch.com', pricing_url: 'https://stytch.com/pricing',
    pricing_model: 'free_tier+usage', has_free_tier: true, free_tier_summary: '10K MAU free',
    starting_paid_tier_usd: 0,
    region_strengths: RX(60, 85, 92, 80, 70), data_residency_options: ['us','eu'],
    compliance_certs: ['SOC2','ISO27001','GDPR','HIPAA'], integration_complexity: 2, setup_time_estimate_minutes: 30,
    primary_languages: ['javascript','typescript','python','go','java'],
    last_funding_round: 'series-b', last_funding_year: 2022, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },

  // ─── PAYMENTS ────────────────────────────────────────────────────────
  { slug: 'stripe', category_id: 'payments', name: 'Stripe', vendor: 'Stripe',
    description: 'Best-in-class developer experience for global card payments + subscriptions + tax + payouts.',
    homepage_url: 'https://stripe.com', pricing_url: 'https://stripe.com/pricing',
    pricing_model: 'usage_only', has_free_tier: true, free_tier_summary: 'No setup fees; 2.9% + $0.30 per transaction',
    starting_paid_tier_usd: 0, pricing_unit: '2.9% + 30¢ per successful transaction',
    region_strengths: RX(45, 92, 98, 85, 80), data_residency_options: ['us','eu','asia-pacific','latam'],
    compliance_certs: ['SOC2','ISO27001','PCI','GDPR'], integration_complexity: 2, setup_time_estimate_minutes: 60,
    primary_languages: ['javascript','typescript','python','ruby','java','go','c#','php','swift','kotlin','dart'],
    last_funding_round: 'series-i', last_funding_year: 2023, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'lemon-squeezy', category_id: 'payments', name: 'Lemon Squeezy', vendor: 'Lemon Squeezy',
    description: 'Merchant of record for digital products + SaaS. Handles tax/VAT globally so you don\'t have to.',
    homepage_url: 'https://lemonsqueezy.com', pricing_url: 'https://lemonsqueezy.com/pricing',
    pricing_model: 'usage_only', has_free_tier: false, starting_paid_tier_usd: 0, pricing_unit: '5% + 50¢ per sale',
    region_strengths: RX(70, 90, 92, 85, 80), data_residency_options: ['us','eu'],
    compliance_certs: ['PCI','GDPR'], integration_complexity: 1, setup_time_estimate_minutes: 30,
    primary_languages: ['javascript','typescript','python','php'],
    last_funding_round: 'profitable_bootstrapped', public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'paddle', category_id: 'payments', name: 'Paddle', vendor: 'Paddle',
    description: 'Merchant of record like Lemon Squeezy. Established player with strong tax + VAT handling.',
    homepage_url: 'https://www.paddle.com', pricing_url: 'https://www.paddle.com/pricing',
    pricing_model: 'usage_only', has_free_tier: true, starting_paid_tier_usd: 0, pricing_unit: '5% + 50¢ per transaction',
    region_strengths: RX(60, 92, 88, 80, 75), data_residency_options: ['us','eu'],
    compliance_certs: ['PCI','SOC2','GDPR'], integration_complexity: 2, setup_time_estimate_minutes: 60,
    primary_languages: ['javascript','typescript','python','ruby','php','java'],
    last_funding_round: 'series-d', last_funding_year: 2022, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'paystack', category_id: 'payments', name: 'Paystack', vendor: 'Paystack (Stripe)',
    description: 'Africa-first payments. Card + bank + mobile money + USSD across Nigeria, Ghana, South Africa, Kenya, Côte d\'Ivoire.',
    homepage_url: 'https://paystack.com', pricing_url: 'https://paystack.com/pricing',
    pricing_model: 'usage_only', has_free_tier: true, starting_paid_tier_usd: 0, pricing_unit: '1.5-3.9% per transaction',
    region_strengths: RX(98, 30, 30, 25, 30), data_residency_options: ['nigeria','south-africa'],
    compliance_certs: ['PCI'], integration_complexity: 2, setup_time_estimate_minutes: 45,
    primary_languages: ['javascript','typescript','python','ruby','php','java'],
    last_funding_round: 'acquired_by_stripe', last_funding_year: 2020, public_incident_frequency: 'medium',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'flutterwave', category_id: 'payments', name: 'Flutterwave', vendor: 'Flutterwave',
    description: 'Pan-African payments. 30+ countries, 150+ currencies, mobile money, cards, bank transfers.',
    homepage_url: 'https://flutterwave.com', pricing_url: 'https://flutterwave.com/us/pricing',
    pricing_model: 'usage_only', has_free_tier: true, starting_paid_tier_usd: 0, pricing_unit: '1.4-3.8% per transaction',
    region_strengths: RX(95, 35, 40, 35, 35), data_residency_options: ['nigeria','south-africa','kenya'],
    compliance_certs: ['PCI'], integration_complexity: 3, setup_time_estimate_minutes: 60,
    primary_languages: ['javascript','typescript','python','php','java'],
    last_funding_round: 'series-d', last_funding_year: 2022, public_incident_frequency: 'medium',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'paypal', category_id: 'payments', name: 'PayPal', vendor: 'PayPal',
    description: 'Mass-market payment rail. Universal recognition; clunky DX vs Stripe.',
    homepage_url: 'https://paypal.com', pricing_url: 'https://www.paypal.com/us/business/fees',
    pricing_model: 'usage_only', has_free_tier: true, starting_paid_tier_usd: 0,
    region_strengths: RX(70, 88, 92, 80, 80), data_residency_options: ['us','eu','asia-pacific'],
    compliance_certs: ['PCI','SOC1','SOC2','GDPR'], integration_complexity: 3, setup_time_estimate_minutes: 90,
    primary_languages: ['javascript','python','java','php','ruby','c#'],
    last_funding_round: 'public', last_funding_year: 2002, public_incident_frequency: 'medium',
    open_source: false, self_hostable: false, data_export_ease: 'difficult' },
  { slug: 'square', category_id: 'payments', name: 'Square', vendor: 'Block (Square)',
    description: 'Strong for in-person + omnichannel commerce; less developer-focused than Stripe.',
    homepage_url: 'https://squareup.com', pricing_url: 'https://squareup.com/us/en/pricing',
    pricing_model: 'usage_only', has_free_tier: true, starting_paid_tier_usd: 0,
    region_strengths: RX(35, 70, 92, 75, 50), data_residency_options: ['us','ca','uk','au','jp','ie','fr','es'],
    compliance_certs: ['PCI','SOC1','SOC2'], integration_complexity: 3, setup_time_estimate_minutes: 60,
    primary_languages: ['javascript','python','ruby','java','php','c#'],
    last_funding_round: 'public', last_funding_year: 2015, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },

  // ─── EMAIL & NOTIFICATIONS ───────────────────────────────────────────
  { slug: 'resend', category_id: 'email', name: 'Resend', vendor: 'Resend',
    description: 'Developer-first transactional email. React Email integration, excellent DX.',
    homepage_url: 'https://resend.com', pricing_url: 'https://resend.com/pricing',
    pricing_model: 'free_tier+usage', has_free_tier: true, free_tier_summary: '3K emails/month',
    starting_paid_tier_usd: 20,
    region_strengths: RX(60, 88, 92, 80, 70), data_residency_options: ['us'],
    compliance_certs: ['SOC2','GDPR'], integration_complexity: 1, setup_time_estimate_minutes: 10,
    primary_languages: ['javascript','typescript','python','ruby','go','php'],
    last_funding_round: 'series-a', last_funding_year: 2024, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'postmark', category_id: 'email', name: 'Postmark', vendor: 'ActiveCampaign',
    description: 'Premium transactional email with the highest deliverability reputation in the category.',
    homepage_url: 'https://postmarkapp.com', pricing_url: 'https://postmarkapp.com/pricing',
    pricing_model: 'subscription', has_free_tier: true, free_tier_summary: '100 emails/month',
    starting_paid_tier_usd: 15,
    region_strengths: RX(60, 88, 92, 78, 70), data_residency_options: ['us','eu'],
    compliance_certs: ['SOC2','GDPR'], integration_complexity: 1, setup_time_estimate_minutes: 15,
    primary_languages: ['javascript','python','ruby','go','php','java','c#'],
    last_funding_round: 'acquired', last_funding_year: 2022, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'sendgrid', category_id: 'email', name: 'SendGrid', vendor: 'Twilio',
    description: 'Enterprise-grade email. Marketing + transactional. Best when you need volume.',
    homepage_url: 'https://sendgrid.com', pricing_url: 'https://sendgrid.com/pricing/',
    pricing_model: 'subscription', has_free_tier: true, free_tier_summary: '100 emails/day forever',
    starting_paid_tier_usd: 19.95,
    region_strengths: RX(70, 90, 95, 85, 75), data_residency_options: ['us','eu'],
    compliance_certs: ['SOC2','ISO27001','HIPAA','GDPR','PCI'], integration_complexity: 2, setup_time_estimate_minutes: 30,
    primary_languages: ['javascript','python','ruby','go','php','java','c#'],
    last_funding_round: 'public', last_funding_year: 2017, public_incident_frequency: 'medium',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'mailgun', category_id: 'email', name: 'Mailgun', vendor: 'Sinch',
    description: 'Developer-focused email API with strong analytics and inbound parsing.',
    homepage_url: 'https://mailgun.com', pricing_url: 'https://www.mailgun.com/pricing/',
    pricing_model: 'subscription', has_free_tier: true, free_tier_summary: '5K emails for 30 days',
    starting_paid_tier_usd: 35,
    region_strengths: RX(60, 88, 92, 80, 75), data_residency_options: ['us','eu'],
    compliance_certs: ['SOC2','GDPR','HIPAA'], integration_complexity: 2, setup_time_estimate_minutes: 30,
    primary_languages: ['javascript','python','ruby','go','php','java','c#'],
    last_funding_round: 'public', last_funding_year: 2020, public_incident_frequency: 'medium',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'loops', category_id: 'email', name: 'Loops', vendor: 'Loops',
    description: 'Email + lifecycle marketing for SaaS. Designed for transactional + nurture in one tool.',
    homepage_url: 'https://loops.so', pricing_url: 'https://loops.so/pricing',
    pricing_model: 'subscription', has_free_tier: true, free_tier_summary: '1K contacts free',
    starting_paid_tier_usd: 49,
    region_strengths: RX(55, 85, 92, 78, 65), data_residency_options: ['us'],
    compliance_certs: ['SOC2','GDPR'], integration_complexity: 1, setup_time_estimate_minutes: 30,
    primary_languages: ['javascript','typescript'],
    last_funding_round: 'seed', last_funding_year: 2024, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'customer-io', category_id: 'email', name: 'Customer.io', vendor: 'Customer.io',
    description: 'Behavior-driven messaging across email, SMS, push. Strong for product-led GTM.',
    homepage_url: 'https://customer.io', pricing_url: 'https://customer.io/pricing/',
    pricing_model: 'subscription', has_free_tier: true, starting_paid_tier_usd: 100,
    region_strengths: RX(60, 88, 92, 80, 75), data_residency_options: ['us','eu'],
    compliance_certs: ['SOC2','GDPR','HIPAA'], integration_complexity: 3, setup_time_estimate_minutes: 120,
    primary_languages: ['javascript','python','ruby','go','php','java'],
    last_funding_round: 'series-a', last_funding_year: 2017, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'twilio', category_id: 'email', name: 'Twilio', vendor: 'Twilio',
    description: 'SMS, voice, WhatsApp, video. The default for programmable communications.',
    homepage_url: 'https://twilio.com', pricing_url: 'https://www.twilio.com/pricing',
    pricing_model: 'usage_only', has_free_tier: true, starting_paid_tier_usd: 0,
    region_strengths: RX(75, 90, 95, 88, 80), data_residency_options: ['us','eu','au','sg','br'],
    compliance_certs: ['SOC2','HIPAA','GDPR','PCI'], integration_complexity: 3, setup_time_estimate_minutes: 60,
    primary_languages: ['javascript','python','ruby','go','php','java','c#'],
    last_funding_round: 'public', last_funding_year: 2016, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },

  // ─── AI MODELS — LLMs ────────────────────────────────────────────────
  { slug: 'anthropic-claude', category_id: 'ai_llm', name: 'Anthropic Claude', vendor: 'Anthropic',
    description: 'Sonnet 4.6 + Opus 4.7. Strongest at long-context reasoning, code, agents, and refusing harmful requests.',
    homepage_url: 'https://anthropic.com', pricing_url: 'https://www.anthropic.com/pricing',
    pricing_model: 'usage_only', has_free_tier: false, starting_paid_tier_usd: 0,
    pricing_unit: 'Sonnet $3 in / $15 out per M tokens; Opus $15 / $75',
    region_strengths: RX(70, 88, 92, 80, 75), data_residency_options: ['us','eu (Bedrock)'],
    compliance_certs: ['SOC2','HIPAA','GDPR'], integration_complexity: 1, setup_time_estimate_minutes: 5,
    primary_languages: ['any (HTTP REST)'],
    last_funding_round: 'series-d', last_funding_year: 2024, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'openai-gpt', category_id: 'ai_llm', name: 'OpenAI GPT', vendor: 'OpenAI',
    description: 'GPT-5 family. Broadest ecosystem, strongest tool / vision capabilities.',
    homepage_url: 'https://openai.com', pricing_url: 'https://openai.com/api/pricing/',
    pricing_model: 'usage_only', has_free_tier: false, starting_paid_tier_usd: 0,
    region_strengths: RX(70, 88, 95, 85, 75), data_residency_options: ['us','eu','asia (Azure)'],
    compliance_certs: ['SOC2','HIPAA','GDPR'], integration_complexity: 1, setup_time_estimate_minutes: 5,
    primary_languages: ['any (HTTP REST)'],
    last_funding_round: 'series-e', last_funding_year: 2024, public_incident_frequency: 'medium',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'google-gemini', category_id: 'ai_llm', name: 'Google Gemini', vendor: 'Google',
    description: 'Gemini 2.x family with strong multimodal + 2M-token context. Cheap at scale.',
    homepage_url: 'https://ai.google.dev', pricing_url: 'https://ai.google.dev/pricing',
    pricing_model: 'free_tier+usage', has_free_tier: true, starting_paid_tier_usd: 0,
    region_strengths: RX(72, 88, 95, 92, 78), data_residency_options: ['multi-region','us','eu','ap'],
    compliance_certs: ['SOC2','ISO27001','HIPAA','GDPR'], integration_complexity: 2, setup_time_estimate_minutes: 15,
    primary_languages: ['any (HTTP REST)'],
    last_funding_round: 'public', last_funding_year: 2004, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'xai-grok', category_id: 'ai_llm', name: 'xAI Grok', vendor: 'xAI',
    description: 'Grok 4 family. Real-time X (Twitter) data integration; aggressive pricing.',
    homepage_url: 'https://x.ai', pricing_url: 'https://x.ai/api',
    pricing_model: 'usage_only', has_free_tier: false, starting_paid_tier_usd: 0,
    region_strengths: RX(60, 80, 92, 75, 65), data_residency_options: ['us'],
    compliance_certs: [], integration_complexity: 1, setup_time_estimate_minutes: 5,
    primary_languages: ['any (HTTP REST)'],
    last_funding_round: 'series-c', last_funding_year: 2024, public_incident_frequency: 'medium',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'deepseek', category_id: 'ai_llm', name: 'DeepSeek', vendor: 'DeepSeek',
    description: 'Cost-leader for reasoning + coding. Open weights for select models. ~10x cheaper than GPT/Claude.',
    homepage_url: 'https://deepseek.com', pricing_url: 'https://api-docs.deepseek.com/quick_start/pricing',
    pricing_model: 'usage_only', has_free_tier: false, starting_paid_tier_usd: 0,
    region_strengths: RX(70, 75, 75, 95, 70), data_residency_options: ['cn','sg'],
    compliance_certs: [], integration_complexity: 1, setup_time_estimate_minutes: 10,
    primary_languages: ['any (HTTP REST)'],
    last_funding_round: 'unknown', public_incident_frequency: 'medium',
    open_source: true, self_hostable: true, data_export_ease: 'trivial' },
  { slug: 'mistral', category_id: 'ai_llm', name: 'Mistral', vendor: 'Mistral AI',
    description: 'European LLM provider with strong open-weight options. EU data residency.',
    homepage_url: 'https://mistral.ai', pricing_url: 'https://mistral.ai/pricing/',
    pricing_model: 'usage_only', has_free_tier: false, starting_paid_tier_usd: 0,
    region_strengths: RX(65, 95, 80, 75, 70), data_residency_options: ['eu'],
    compliance_certs: ['SOC2','GDPR'], integration_complexity: 1, setup_time_estimate_minutes: 10,
    primary_languages: ['any (HTTP REST)'],
    last_funding_round: 'series-b', last_funding_year: 2024, public_incident_frequency: 'low',
    open_source: true, self_hostable: true, data_export_ease: 'trivial' },
  { slug: 'cohere', category_id: 'ai_llm', name: 'Cohere', vendor: 'Cohere',
    description: 'Enterprise-focused LLMs with strong RAG + reranking. Canadian data residency option.',
    homepage_url: 'https://cohere.com', pricing_url: 'https://cohere.com/pricing',
    pricing_model: 'usage_only', has_free_tier: true, starting_paid_tier_usd: 0,
    region_strengths: RX(65, 88, 88, 80, 70), data_residency_options: ['us','eu','ca'],
    compliance_certs: ['SOC2','HIPAA','GDPR'], integration_complexity: 2, setup_time_estimate_minutes: 15,
    primary_languages: ['any (HTTP REST)'],
    last_funding_round: 'series-d', last_funding_year: 2024, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'meta-llama', category_id: 'ai_llm', name: 'Meta Llama', vendor: 'Meta',
    description: 'Open-weight Llama 4 family. Run via Together / Groq / Bedrock / self-host.',
    homepage_url: 'https://www.llama.com', pricing_url: 'https://www.together.ai/pricing',
    pricing_model: 'open_source_self_host', has_free_tier: true, starting_paid_tier_usd: 0,
    region_strengths: RX(75, 80, 85, 80, 75), data_residency_options: ['wherever you run inference'],
    compliance_certs: [], integration_complexity: 3, setup_time_estimate_minutes: 60,
    primary_languages: ['any'],
    last_funding_round: 'public', last_funding_year: 2012, public_incident_frequency: 'low',
    open_source: true, self_hostable: true, data_export_ease: 'trivial' },

  // ─── AI MODELS — EMBEDDINGS ──────────────────────────────────────────
  { slug: 'voyage-ai', category_id: 'ai_embeddings', name: 'Voyage AI', vendor: 'Voyage AI',
    description: 'voyage-3 family. Best-in-class quality for retrieval; specialised models for code, finance, law.',
    homepage_url: 'https://www.voyageai.com', pricing_url: 'https://docs.voyageai.com/docs/pricing',
    pricing_model: 'usage_only', has_free_tier: true, starting_paid_tier_usd: 0,
    pricing_unit: '$0.02-0.18 per M tokens',
    region_strengths: RX(60, 85, 92, 80, 70), data_residency_options: ['us'],
    compliance_certs: ['SOC2'], integration_complexity: 1, setup_time_estimate_minutes: 5,
    primary_languages: ['any (HTTP REST)'],
    last_funding_round: 'acquired_by_mongodb', last_funding_year: 2025, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'trivial' },
  { slug: 'openai-embeddings', category_id: 'ai_embeddings', name: 'OpenAI Embeddings', vendor: 'OpenAI',
    description: 'text-embedding-3-large + small. Solid baseline, broad ecosystem.',
    homepage_url: 'https://platform.openai.com/docs/guides/embeddings', pricing_url: 'https://openai.com/api/pricing/',
    pricing_model: 'usage_only', has_free_tier: false, starting_paid_tier_usd: 0,
    region_strengths: RX(70, 88, 95, 85, 75), data_residency_options: ['us','eu','ap'],
    compliance_certs: ['SOC2','HIPAA','GDPR'], integration_complexity: 1, setup_time_estimate_minutes: 5,
    primary_languages: ['any (HTTP REST)'],
    last_funding_round: 'series-e', last_funding_year: 2024, public_incident_frequency: 'medium',
    open_source: false, self_hostable: false, data_export_ease: 'trivial' },
  { slug: 'cohere-embeddings', category_id: 'ai_embeddings', name: 'Cohere Embed', vendor: 'Cohere',
    description: 'Embed v3 with strong multilingual + reranking complement.',
    homepage_url: 'https://cohere.com/embed', pricing_url: 'https://cohere.com/pricing',
    pricing_model: 'usage_only', has_free_tier: true, starting_paid_tier_usd: 0,
    region_strengths: RX(65, 88, 88, 80, 70), data_residency_options: ['us','eu','ca'],
    compliance_certs: ['SOC2','HIPAA','GDPR'], integration_complexity: 2, setup_time_estimate_minutes: 10,
    primary_languages: ['any (HTTP REST)'],
    last_funding_round: 'series-d', last_funding_year: 2024, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'trivial' },
  { slug: 'jina', category_id: 'ai_embeddings', name: 'Jina', vendor: 'Jina AI',
    description: 'Open-source-friendly embedding + reranker provider. Strong multilingual.',
    homepage_url: 'https://jina.ai', pricing_url: 'https://jina.ai/pricing',
    pricing_model: 'free_tier+usage', has_free_tier: true, starting_paid_tier_usd: 0,
    region_strengths: RX(65, 88, 85, 88, 70), data_residency_options: ['us','eu'],
    compliance_certs: ['GDPR'], integration_complexity: 1, setup_time_estimate_minutes: 10,
    primary_languages: ['any (HTTP REST)'],
    last_funding_round: 'series-a', last_funding_year: 2023, public_incident_frequency: 'low',
    open_source: true, self_hostable: true, data_export_ease: 'trivial' },
  { slug: 'bge', category_id: 'ai_embeddings', name: 'BGE (BAAI)', vendor: 'BAAI',
    description: 'Open-weight Chinese-research embedding family. Best-in-class for fully self-hosted use.',
    homepage_url: 'https://huggingface.co/BAAI', pricing_model: 'open_source_self_host', has_free_tier: true, starting_paid_tier_usd: 0,
    region_strengths: RX(70, 75, 78, 92, 70), data_residency_options: ['wherever you run inference'],
    compliance_certs: [], integration_complexity: 3, setup_time_estimate_minutes: 60,
    primary_languages: ['python'],
    last_funding_round: 'unknown', public_incident_frequency: 'unknown',
    open_source: true, self_hostable: true, data_export_ease: 'trivial' },

  // ─── AI MODELS — SPECIALIZED ─────────────────────────────────────────
  { slug: 'perplexity', category_id: 'ai_specialized', name: 'Perplexity API', vendor: 'Perplexity',
    description: 'Web-search-grounded LLM. Best for "answer with current sources" queries.',
    homepage_url: 'https://docs.perplexity.ai', pricing_url: 'https://docs.perplexity.ai/guides/pricing',
    pricing_model: 'usage_only', has_free_tier: true, starting_paid_tier_usd: 0,
    region_strengths: RX(65, 85, 92, 80, 70), data_residency_options: ['us'],
    compliance_certs: [], integration_complexity: 1, setup_time_estimate_minutes: 5,
    primary_languages: ['any (HTTP REST)'],
    last_funding_round: 'series-c', last_funding_year: 2024, public_incident_frequency: 'medium',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'elevenlabs', category_id: 'ai_specialized', name: 'ElevenLabs', vendor: 'ElevenLabs',
    description: 'Best voice cloning + speech synthesis. 30+ languages.',
    homepage_url: 'https://elevenlabs.io', pricing_url: 'https://elevenlabs.io/pricing',
    pricing_model: 'subscription', has_free_tier: true, starting_paid_tier_usd: 5,
    region_strengths: RX(70, 90, 92, 85, 78), data_residency_options: ['us'],
    compliance_certs: ['SOC2'], integration_complexity: 1, setup_time_estimate_minutes: 10,
    primary_languages: ['javascript','typescript','python'],
    last_funding_round: 'series-c', last_funding_year: 2025, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'replicate', category_id: 'ai_specialized', name: 'Replicate', vendor: 'Replicate',
    description: 'Run any open-source ML model via API. Good for image / video / audio generation.',
    homepage_url: 'https://replicate.com', pricing_url: 'https://replicate.com/pricing',
    pricing_model: 'usage_only', has_free_tier: true, starting_paid_tier_usd: 0,
    region_strengths: RX(60, 85, 92, 78, 70), data_residency_options: ['us'],
    compliance_certs: ['SOC2'], integration_complexity: 1, setup_time_estimate_minutes: 5,
    primary_languages: ['javascript','typescript','python'],
    last_funding_round: 'series-b', last_funding_year: 2024, public_incident_frequency: 'medium',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'browserless', category_id: 'ai_specialized', name: 'Browserless', vendor: 'Browserless',
    description: 'Hosted Chrome-as-a-service. Used by FlowAI\'s Super Customer Agent for full-render web capture.',
    homepage_url: 'https://browserless.io', pricing_url: 'https://browserless.io/pricing',
    pricing_model: 'subscription', has_free_tier: true, starting_paid_tier_usd: 50,
    region_strengths: RX(60, 88, 92, 78, 70), data_residency_options: ['us','eu'],
    compliance_certs: ['SOC2'], integration_complexity: 2, setup_time_estimate_minutes: 15,
    primary_languages: ['javascript','typescript','python'],
    last_funding_round: 'profitable_bootstrapped', public_incident_frequency: 'low',
    open_source: true, self_hostable: true, data_export_ease: 'trivial' },

  // ─── BACKGROUND JOBS & QUEUES ────────────────────────────────────────
  { slug: 'inngest', category_id: 'jobs', name: 'Inngest', vendor: 'Inngest',
    description: 'Durable workflows triggered by events. Strong DX for TypeScript; cron + retries built-in.',
    homepage_url: 'https://inngest.com', pricing_url: 'https://inngest.com/pricing',
    pricing_model: 'free_tier+usage', has_free_tier: true, free_tier_summary: '50K runs/month',
    starting_paid_tier_usd: 50,
    region_strengths: RX(60, 85, 92, 78, 70), data_residency_options: ['us','eu'],
    compliance_certs: ['SOC2','GDPR'], integration_complexity: 1, setup_time_estimate_minutes: 15,
    primary_languages: ['javascript','typescript','python','go'],
    last_funding_round: 'series-a', last_funding_year: 2024, public_incident_frequency: 'low',
    open_source: true, self_hostable: true, data_export_ease: 'trivial' },
  { slug: 'trigger-dev', category_id: 'jobs', name: 'Trigger.dev', vendor: 'Trigger.dev',
    description: 'Background jobs as TypeScript code. Strong observability; auto retries.',
    homepage_url: 'https://trigger.dev', pricing_url: 'https://trigger.dev/pricing',
    pricing_model: 'free_tier+usage', has_free_tier: true, starting_paid_tier_usd: 20,
    region_strengths: RX(60, 88, 90, 78, 70), data_residency_options: ['us','eu'],
    compliance_certs: ['SOC2'], integration_complexity: 1, setup_time_estimate_minutes: 15,
    primary_languages: ['javascript','typescript'],
    last_funding_round: 'seed', last_funding_year: 2024, public_incident_frequency: 'low',
    open_source: true, self_hostable: true, data_export_ease: 'trivial' },
  { slug: 'temporal', category_id: 'jobs', name: 'Temporal', vendor: 'Temporal Technologies',
    description: 'Durable workflows for mission-critical systems. Steeper learning curve; massive scale.',
    homepage_url: 'https://temporal.io', pricing_url: 'https://temporal.io/pricing',
    pricing_model: 'usage_only', has_free_tier: true, starting_paid_tier_usd: 0,
    region_strengths: RX(60, 88, 92, 80, 70), data_residency_options: ['us','eu','ap'],
    compliance_certs: ['SOC2','HIPAA','GDPR','PCI'], integration_complexity: 5, setup_time_estimate_minutes: 240,
    primary_languages: ['typescript','javascript','python','go','java','php','ruby','c#'],
    last_funding_round: 'series-c', last_funding_year: 2024, public_incident_frequency: 'low',
    open_source: true, self_hostable: true, data_export_ease: 'trivial' },
  { slug: 'bullmq', category_id: 'jobs', name: 'BullMQ', vendor: 'Taskforce.sh',
    description: 'Open-source Redis-backed job queue. Self-hosted; battle-tested in Node ecosystem.',
    homepage_url: 'https://docs.bullmq.io', pricing_model: 'open_source_self_host', has_free_tier: true, starting_paid_tier_usd: 0,
    region_strengths: RX(80, 80, 80, 80, 80), data_residency_options: ['wherever your Redis is'],
    compliance_certs: [], integration_complexity: 3, setup_time_estimate_minutes: 60,
    primary_languages: ['javascript','typescript','python'],
    last_funding_round: 'unknown', public_incident_frequency: 'unknown',
    open_source: true, self_hostable: true, data_export_ease: 'trivial' },
  { slug: 'cloudflare-queues', category_id: 'jobs', name: 'Cloudflare Queues', vendor: 'Cloudflare',
    description: 'Workers-native queues with global delivery. Cheapest at scale.',
    homepage_url: 'https://developers.cloudflare.com/queues/', pricing_url: 'https://www.cloudflare.com/plans/developer-platform/',
    pricing_model: 'free_tier+usage', has_free_tier: true, starting_paid_tier_usd: 5,
    region_strengths: RX(85, 92, 92, 90, 82), data_residency_options: ['global-edge'],
    compliance_certs: ['SOC2','ISO27001','HIPAA','GDPR'], integration_complexity: 2, setup_time_estimate_minutes: 30,
    primary_languages: ['javascript','typescript','rust','python'],
    last_funding_round: 'public', last_funding_year: 2019, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },

  // ─── OBSERVABILITY ───────────────────────────────────────────────────
  { slug: 'axiom', category_id: 'observability', name: 'Axiom', vendor: 'Axiom',
    description: 'Cost-efficient logs + traces. Generous free tier; SQL-style query.',
    homepage_url: 'https://axiom.co', pricing_url: 'https://axiom.co/pricing',
    pricing_model: 'free_tier+usage', has_free_tier: true, free_tier_summary: '500GB/month free',
    starting_paid_tier_usd: 25,
    region_strengths: RX(60, 88, 92, 80, 72), data_residency_options: ['us','eu'],
    compliance_certs: ['SOC2','GDPR'], integration_complexity: 1, setup_time_estimate_minutes: 15,
    primary_languages: ['javascript','typescript','python','go','rust'],
    last_funding_round: 'seed', last_funding_year: 2023, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'datadog', category_id: 'observability', name: 'Datadog', vendor: 'Datadog',
    description: 'Enterprise observability with metrics, logs, APM, RUM. Expensive but comprehensive.',
    homepage_url: 'https://datadoghq.com', pricing_url: 'https://www.datadoghq.com/pricing/',
    pricing_model: 'subscription', has_free_tier: true, starting_paid_tier_usd: 15,
    region_strengths: RX(70, 92, 95, 88, 78), data_residency_options: ['us','eu','asia-pacific'],
    compliance_certs: ['SOC2','ISO27001','HIPAA','GDPR','PCI','FedRAMP'], integration_complexity: 3, setup_time_estimate_minutes: 60,
    primary_languages: ['any'],
    last_funding_round: 'public', last_funding_year: 2019, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'difficult' },
  { slug: 'sentry', category_id: 'observability', name: 'Sentry', vendor: 'Sentry',
    description: 'Error tracking + performance monitoring. The default for client + server crash visibility.',
    homepage_url: 'https://sentry.io', pricing_url: 'https://sentry.io/pricing/',
    pricing_model: 'free_tier+usage', has_free_tier: true, starting_paid_tier_usd: 26,
    region_strengths: RX(65, 90, 92, 82, 75), data_residency_options: ['us','eu'],
    compliance_certs: ['SOC2','HIPAA','GDPR','PCI'], integration_complexity: 1, setup_time_estimate_minutes: 15,
    primary_languages: ['javascript','typescript','python','ruby','go','php','java','swift','kotlin','dart','rust'],
    last_funding_round: 'series-e', last_funding_year: 2022, public_incident_frequency: 'low',
    open_source: true, self_hostable: true, data_export_ease: 'trivial' },
  { slug: 'better-stack', category_id: 'observability', name: 'Better Stack', vendor: 'Better Stack',
    description: 'Logs + uptime + incident management. Strong on the "human layer" of ops.',
    homepage_url: 'https://betterstack.com', pricing_url: 'https://betterstack.com/pricing',
    pricing_model: 'subscription', has_free_tier: true, starting_paid_tier_usd: 25,
    region_strengths: RX(65, 90, 92, 80, 72), data_residency_options: ['us','eu'],
    compliance_certs: ['SOC2','GDPR'], integration_complexity: 2, setup_time_estimate_minutes: 30,
    primary_languages: ['javascript','typescript','python','go','ruby'],
    last_funding_round: 'series-a', last_funding_year: 2024, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'highlight', category_id: 'observability', name: 'Highlight', vendor: 'Highlight',
    description: 'Open-source session replay + error monitoring. Self-host or cloud.',
    homepage_url: 'https://highlight.io', pricing_url: 'https://www.highlight.io/pricing',
    pricing_model: 'free_tier+usage', has_free_tier: true, starting_paid_tier_usd: 50,
    region_strengths: RX(60, 85, 90, 78, 70), data_residency_options: ['us','eu'],
    compliance_certs: ['SOC2'], integration_complexity: 2, setup_time_estimate_minutes: 30,
    primary_languages: ['javascript','typescript','go','python'],
    last_funding_round: 'series-a', last_funding_year: 2024, public_incident_frequency: 'low',
    open_source: true, self_hostable: true, data_export_ease: 'trivial' },

  // ─── ANALYTICS ───────────────────────────────────────────────────────
  { slug: 'posthog', category_id: 'analytics', name: 'PostHog', vendor: 'PostHog',
    description: 'Open-source product analytics + feature flags + session replay + experiments. All-in-one.',
    homepage_url: 'https://posthog.com', pricing_url: 'https://posthog.com/pricing',
    pricing_model: 'free_tier+usage', has_free_tier: true, free_tier_summary: '1M events/month',
    starting_paid_tier_usd: 0,
    region_strengths: RX(70, 90, 92, 80, 75), data_residency_options: ['us','eu'],
    compliance_certs: ['SOC2','HIPAA','GDPR'], integration_complexity: 2, setup_time_estimate_minutes: 30,
    primary_languages: ['javascript','typescript','python','ruby','go','php','java','swift','kotlin','dart'],
    last_funding_round: 'series-c', last_funding_year: 2024, public_incident_frequency: 'low',
    open_source: true, self_hostable: true, data_export_ease: 'trivial' },
  { slug: 'mixpanel', category_id: 'analytics', name: 'Mixpanel', vendor: 'Mixpanel',
    description: 'Funnel + cohort analysis with strong self-serve UI. Generous free tier.',
    homepage_url: 'https://mixpanel.com', pricing_url: 'https://mixpanel.com/pricing/',
    pricing_model: 'free_tier+usage', has_free_tier: true, starting_paid_tier_usd: 25,
    region_strengths: RX(65, 88, 92, 80, 75), data_residency_options: ['us','eu'],
    compliance_certs: ['SOC2','HIPAA','GDPR'], integration_complexity: 2, setup_time_estimate_minutes: 30,
    primary_languages: ['javascript','python','swift','kotlin','dart'],
    last_funding_round: 'series-c', last_funding_year: 2021, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'amplitude', category_id: 'analytics', name: 'Amplitude', vendor: 'Amplitude',
    description: 'Enterprise product analytics. Strong for retention + behavioral cohort analysis.',
    homepage_url: 'https://amplitude.com', pricing_url: 'https://amplitude.com/pricing',
    pricing_model: 'subscription', has_free_tier: true, starting_paid_tier_usd: 49,
    region_strengths: RX(65, 88, 95, 82, 75), data_residency_options: ['us','eu'],
    compliance_certs: ['SOC2','HIPAA','GDPR','ISO27001'], integration_complexity: 3, setup_time_estimate_minutes: 60,
    primary_languages: ['javascript','python','swift','kotlin','java'],
    last_funding_round: 'public', last_funding_year: 2021, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'plausible', category_id: 'analytics', name: 'Plausible', vendor: 'Plausible',
    description: 'Privacy-first website analytics. GDPR/CCPA-clean by default; cookieless.',
    homepage_url: 'https://plausible.io', pricing_url: 'https://plausible.io/#pricing',
    pricing_model: 'subscription', has_free_tier: false, starting_paid_tier_usd: 9,
    region_strengths: RX(70, 95, 88, 80, 75), data_residency_options: ['eu'],
    compliance_certs: ['GDPR'], integration_complexity: 1, setup_time_estimate_minutes: 5,
    primary_languages: ['any'],
    last_funding_round: 'profitable_bootstrapped', public_incident_frequency: 'low',
    open_source: true, self_hostable: true, data_export_ease: 'trivial' },
  { slug: 'vercel-analytics', category_id: 'analytics', name: 'Vercel Analytics', vendor: 'Vercel',
    description: 'Bundled analytics + speed insights for Vercel-deployed sites. Privacy-friendly.',
    homepage_url: 'https://vercel.com/analytics', pricing_url: 'https://vercel.com/pricing',
    pricing_model: 'subscription', has_free_tier: true, starting_paid_tier_usd: 10,
    region_strengths: RX(65, 88, 95, 80, 72), data_residency_options: ['us','eu'],
    compliance_certs: ['SOC2','GDPR'], integration_complexity: 1, setup_time_estimate_minutes: 5,
    primary_languages: ['javascript','typescript'],
    last_funding_round: 'series-d', last_funding_year: 2021, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'june', category_id: 'analytics', name: 'June', vendor: 'June',
    description: 'Pre-built B2B SaaS analytics dashboards. No setup; auto-detects key metrics.',
    homepage_url: 'https://june.so', pricing_url: 'https://june.so/pricing',
    pricing_model: 'free_tier+usage', has_free_tier: true, starting_paid_tier_usd: 149,
    region_strengths: RX(60, 85, 90, 75, 70), data_residency_options: ['us'],
    compliance_certs: ['SOC2','GDPR'], integration_complexity: 1, setup_time_estimate_minutes: 15,
    primary_languages: ['javascript','typescript','python','ruby'],
    last_funding_round: 'seed', last_funding_year: 2023, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },

  // ─── STORAGE & CDN ───────────────────────────────────────────────────
  { slug: 'cloudflare-r2', category_id: 'storage', name: 'Cloudflare R2', vendor: 'Cloudflare',
    description: 'S3-compatible object storage with zero egress fees. Cheapest for high-egress workloads.',
    homepage_url: 'https://www.cloudflare.com/products/r2/', pricing_url: 'https://www.cloudflare.com/plans/developer-platform/',
    pricing_model: 'usage_only', has_free_tier: true, free_tier_summary: '10GB/month free',
    starting_paid_tier_usd: 0,
    region_strengths: RX(85, 92, 92, 90, 82), data_residency_options: ['global-edge'],
    compliance_certs: ['SOC2','ISO27001','HIPAA','GDPR'], integration_complexity: 2, setup_time_estimate_minutes: 30,
    primary_languages: ['any (S3 SDK)'],
    last_funding_round: 'public', last_funding_year: 2019, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'trivial' },
  { slug: 'aws-s3', category_id: 'storage', name: 'AWS S3', vendor: 'AWS',
    description: 'The reference standard for object storage. Costly egress; widest tooling support.',
    homepage_url: 'https://aws.amazon.com/s3/', pricing_url: 'https://aws.amazon.com/s3/pricing/',
    pricing_model: 'usage_only', has_free_tier: true, starting_paid_tier_usd: 0,
    region_strengths: RX(75, 92, 95, 92, 78), data_residency_options: ['30+ regions'],
    compliance_certs: ['SOC2','ISO27001','HIPAA','GDPR','PCI','FedRAMP'], integration_complexity: 2, setup_time_estimate_minutes: 30,
    primary_languages: ['any'],
    last_funding_round: 'public', last_funding_year: 2006, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'vercel-blob', category_id: 'storage', name: 'Vercel Blob', vendor: 'Vercel',
    description: 'Object storage tightly integrated with Vercel projects. Convenient, not cheapest.',
    homepage_url: 'https://vercel.com/storage/blob', pricing_url: 'https://vercel.com/pricing',
    pricing_model: 'free_tier+usage', has_free_tier: true, starting_paid_tier_usd: 0,
    region_strengths: RX(60, 88, 92, 80, 70), data_residency_options: ['us','eu'],
    compliance_certs: ['SOC2','GDPR'], integration_complexity: 1, setup_time_estimate_minutes: 10,
    primary_languages: ['javascript','typescript'],
    last_funding_round: 'series-d', last_funding_year: 2021, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'bunny-net', category_id: 'storage', name: 'Bunny.net', vendor: 'Bunny.net',
    description: 'Mid-priced CDN + storage with strong global PoPs. Excellent perf-per-dollar.',
    homepage_url: 'https://bunny.net', pricing_url: 'https://bunny.net/pricing/',
    pricing_model: 'usage_only', has_free_tier: false, starting_paid_tier_usd: 1,
    region_strengths: RX(80, 92, 90, 88, 80), data_residency_options: ['100+ PoPs globally'],
    compliance_certs: ['ISO27001','GDPR'], integration_complexity: 2, setup_time_estimate_minutes: 30,
    primary_languages: ['any'],
    last_funding_round: 'profitable_bootstrapped', public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'cloudinary', category_id: 'storage', name: 'Cloudinary', vendor: 'Cloudinary',
    description: 'Image + video transformation + storage + CDN. Best DX for media-heavy apps.',
    homepage_url: 'https://cloudinary.com', pricing_url: 'https://cloudinary.com/pricing',
    pricing_model: 'free_tier+usage', has_free_tier: true, starting_paid_tier_usd: 99,
    region_strengths: RX(65, 88, 95, 82, 75), data_residency_options: ['us','eu','ap'],
    compliance_certs: ['SOC2','ISO27001','HIPAA','GDPR'], integration_complexity: 1, setup_time_estimate_minutes: 15,
    primary_languages: ['javascript','python','ruby','java','php','swift','kotlin'],
    last_funding_round: 'series-f', last_funding_year: 2022, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },

  // ─── GTM & MARKETING TOOLS ───────────────────────────────────────────
  { slug: 'cal-com', category_id: 'gtm', name: 'Cal.com', vendor: 'Cal.com',
    description: 'Open-source scheduling. Self-host or cloud. API + embed widgets.',
    homepage_url: 'https://cal.com', pricing_url: 'https://cal.com/pricing',
    pricing_model: 'free_tier+usage', has_free_tier: true, starting_paid_tier_usd: 12,
    region_strengths: RX(75, 90, 90, 80, 75), data_residency_options: ['eu','us'],
    compliance_certs: ['SOC2','GDPR','HIPAA'], integration_complexity: 1, setup_time_estimate_minutes: 15,
    primary_languages: ['javascript','typescript'],
    last_funding_round: 'series-a', last_funding_year: 2024, public_incident_frequency: 'low',
    open_source: true, self_hostable: true, data_export_ease: 'trivial' },
  { slug: 'calendly', category_id: 'gtm', name: 'Calendly', vendor: 'Calendly',
    description: 'Mass-market scheduling. Strong integrations; less flexible than Cal.com.',
    homepage_url: 'https://calendly.com', pricing_url: 'https://calendly.com/pricing',
    pricing_model: 'subscription', has_free_tier: true, starting_paid_tier_usd: 12,
    region_strengths: RX(65, 88, 95, 82, 75), data_residency_options: ['us','eu'],
    compliance_certs: ['SOC2','HIPAA','GDPR'], integration_complexity: 1, setup_time_estimate_minutes: 10,
    primary_languages: ['any (HTTP REST)'],
    last_funding_round: 'series-b', last_funding_year: 2021, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'linear', category_id: 'gtm', name: 'Linear', vendor: 'Linear',
    description: 'Best-in-class issue tracker for product teams. Strong API + Slack integration.',
    homepage_url: 'https://linear.app', pricing_url: 'https://linear.app/pricing',
    pricing_model: 'subscription', has_free_tier: true, starting_paid_tier_usd: 8,
    region_strengths: RX(60, 90, 95, 80, 70), data_residency_options: ['us'],
    compliance_certs: ['SOC2','GDPR'], integration_complexity: 1, setup_time_estimate_minutes: 10,
    primary_languages: ['any (GraphQL)'],
    last_funding_round: 'series-b', last_funding_year: 2022, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
  { slug: 'notion', category_id: 'gtm', name: 'Notion', vendor: 'Notion Labs',
    description: 'Docs + wiki + lightweight CMS. Pairs with Notion API for landing-page content.',
    homepage_url: 'https://notion.so', pricing_url: 'https://www.notion.so/pricing',
    pricing_model: 'subscription', has_free_tier: true, starting_paid_tier_usd: 10,
    region_strengths: RX(60, 88, 95, 88, 72), data_residency_options: ['us','eu','asia'],
    compliance_certs: ['SOC2','HIPAA','GDPR','ISO27001'], integration_complexity: 1, setup_time_estimate_minutes: 15,
    primary_languages: ['any (REST API)'],
    last_funding_round: 'series-c', last_funding_year: 2021, public_incident_frequency: 'low',
    open_source: false, self_hostable: false, data_export_ease: 'moderate' },
];

// ─── Convenience iterators ─────────────────────────────────────────────

export const TOOLS_BY_SLUG = Object.fromEntries(TOOLS.map((t) => [t.slug, t]));
export const TOOLS_BY_CATEGORY = TOOLS.reduce((acc, t) => {
  (acc[t.category_id] ||= []).push(t);
  return acc;
}, {});

export function listCategories() {
  return TOOL_CATEGORIES.slice().sort((a, b) => a.display_order - b.display_order);
}

export function listToolsForCategory(categoryId) {
  return TOOLS_BY_CATEGORY[categoryId] || [];
}

export function getTool(slug) {
  return TOOLS_BY_SLUG[slug] || null;
}

// Step → categories mapping derived from TOOL_CATEGORIES.step_numbers.
export function categoriesForStep(stepNumber) {
  return TOOL_CATEGORIES.filter((c) => c.step_numbers.includes(stepNumber));
}
