/**
 * reportGenerator — W3 clearance-report producer.
 * ---------------------------------------------------------------------------
 * Owner:       /src/lib/audits/reportGenerator.js     (W3 territory)
 * Consumes:    /src/lib/governance/ScoreEvaluator.js (W2, read-only)
 *              /src/lib/agents/MessageSchema.js      (W2, read-only)
 *
 * generateClearanceReport(governanceEval, readinessEval, deps)
 *   - Combines a governance + readiness evaluation via W2.clearanceDecision().
 *   - Builds a markdown report with per-criterion failure breakdown.
 *   - Publishes `system.clearance.decision.v1` to deps.messageBus.
 *   - Returns { markdown, decision, envelope } (frozen).
 *
 * The literal threshold (95) is echoed in the report so any downstream
 * consumer reading the markdown can detect threshold drift without
 * importing CLEARANCE_THRESHOLD.
 * ---------------------------------------------------------------------------
 */

'use strict';

import {
  CLEARANCE_THRESHOLD,
  clearanceDecision,
} from '../governance/ScoreEvaluator.js';

function _defaultDeps() {
  return {
    clock: { now: () => Date.now() },
    messageBus: { publish: async () => {} },
  };
}

function _renderCriteriaSection(label, evaluation) {
  const lines = [`### ${label} — score ${evaluation.score} (rubric ${evaluation.rubricVersion})`];
  if (!evaluation.failures || evaluation.failures.length === 0) {
    lines.push('No failing criteria.');
    return lines.join('\n');
  }
  lines.push('');
  lines.push('| Criterion | Score | Notes |');
  lines.push('|---|---|---|');
  for (const f of evaluation.failures) {
    const safeNotes = String(f.notes ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
    lines.push(`| ${f.id} | ${f.score} | ${safeNotes} |`);
  }
  lines.push('');
  lines.push('Evidence:');
  for (const f of evaluation.failures) {
    lines.push(`- **${f.id}**: ${JSON.stringify(f.evidence)}`);
  }
  return lines.join('\n');
}

export async function generateClearanceReport(governanceEval, readinessEval, deps = {}) {
  if (!governanceEval || typeof governanceEval !== 'object') {
    throw new Error('reportGenerator: governanceEval required');
  }
  if (!readinessEval || typeof readinessEval !== 'object') {
    throw new Error('reportGenerator: readinessEval required');
  }
  const resolved = { ..._defaultDeps(), ...deps };
  const decisionRec = clearanceDecision(governanceEval, readinessEval);

  const markdown = [
    `# Clearance Report — ${decisionRec.targetType}:${decisionRec.targetId}`,
    '',
    `**Decision:** \`${decisionRec.decision}\``,
    `**Clearance threshold:** ${CLEARANCE_THRESHOLD} (echoed literal for drift detection)`,
    `**Governance score:** ${decisionRec.governanceScore}`,
    `**Readiness score:** ${decisionRec.readinessScore}`,
    '',
    '---',
    '',
    '## Governance',
    '',
    _renderCriteriaSection('Governance failures', governanceEval),
    '',
    '## Readiness',
    '',
    _renderCriteriaSection('Readiness failures', readinessEval),
    '',
    '---',
    '',
    `*Generated by W3 reportGenerator. ${decisionRec.failures.length} failure(s) total.*`,
    '',
  ].join('\n');

  const at = resolved.clock.now();
  const payload = {
    targetType: decisionRec.targetType,
    targetId: decisionRec.targetId,
    governanceScore: decisionRec.governanceScore,
    readinessScore: decisionRec.readinessScore,
    decision: decisionRec.decision,
  };
  const envelope = Object.freeze({
    topic: 'system.clearance.decision.v1',
    payload,
    from: { agentId: 'system', productScope: 'flowai' },
    at,
  });
  await resolved.messageBus.publish(envelope);

  return Object.freeze({
    markdown,
    decision: decisionRec.decision,
    envelope,
  });
}

export { CLEARANCE_THRESHOLD };
