// ─── CAPABILITY TRANSFER PAGE ────────────────────────────────────────────────
import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { RefreshCw, Shield, Copy, Check, Zap, Loader2, Package } from 'lucide-react';

function CopyBtn({ text }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      onClick={() => { navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 2000); }}
      className="flex items-center gap-1.5 text-xs border border-border rounded-md px-3 py-1.5 text-muted-foreground hover:text-foreground transition-all"
    >
      {copied ? <><Check className="h-3.5 w-3.5 text-emerald-400" /> Copied!</> : <><Copy className="h-3.5 w-3.5" /> Copy Sprint</>}
    </button>
  );
}

const CAPABILITIES = [
  {
    id: 'self-renewal',
    icon: RefreshCw,
    label: 'Self-Renewal',
    color: 'border-primary/50 bg-primary/5 text-primary',
    desc: 'Installs self-test, self-heal, self-monitor widget, and governance hook into the target product.',
    components: ['Self-Test Engine', 'Self-Heal Module', 'Self-Monitor Dashboard Widget', 'FlowAI Governance Hook'],
    detailPath: '/capability-packages/self-renewal',
    installPath: '/capability-packages/self-renewal/install',
  },
  {
    id: 'self-protection',
    icon: Shield,
    label: 'Self-Protection',
    color: 'border-red-500/50 bg-red-500/5 text-red-400',
    desc: 'Installs anti-crawling, content protection, IP notice footer, and demo environment disclaimer.',
    components: ['Anti-Crawling Bot Detection', 'Content Protection & Watermarks', 'IP Notice Footer', 'Demo Environment Disclaimer'],
    detailPath: '/capability-packages/self-protection',
    installPath: '/capability-packages/self-protection/install',
  },
];

function buildConsolidatedSprint(capabilityId, targetUrl) {
  const productName = targetUrl ? new URL(targetUrl.startsWith('http') ? targetUrl : `https://${targetUrl}`).hostname.replace('www.', '') : 'target-product';

  if (capabilityId === 'self-renewal') {
    return `━━━ CONSOLIDATED SELF-RENEWAL SPRINT ━━━
Target: ${productName}
Generated by FlowAI v0.1

This consolidated sprint installs all four Self-Renewal components simultaneously.

STEP 1: Create functions/selfTest.js (see Self-Renewal Component 1)
STEP 2: Create functions/selfHeal.js (see Self-Renewal Component 2)
STEP 3: Create components/dashboard/SelfMonitorWidget.jsx (see Component 3)
STEP 4: Create functions/governanceHook.js (see Component 4)
STEP 5: In AppLayout, add useEffect to run selfTest on mount
STEP 6: Add SelfMonitorWidget to Dashboard page
STEP 7: Create a Scheduled Automation (daily) calling selfTest function

Paste this into ${productName}'s Base44 project chat:
"Please install the Self-Renewal package for ${productName}. Create: (1) functions/selfTest.js that tests entity accessibility and logs results to GovernanceAuditLog, (2) functions/selfHeal.js that clears stale sessions, (3) components/dashboard/SelfMonitorWidget.jsx showing last test result and Run Test button, (4) functions/governanceHook.js that logs governance events. Add SelfMonitorWidget to the dashboard. Set up a daily scheduled automation for selfTest."`;
  }

  return `━━━ CONSOLIDATED SELF-PROTECTION SPRINT ━━━
Target: ${productName}
Generated by FlowAI v0.1

This consolidated sprint installs all four Self-Protection components simultaneously.

STEP 1: Create lib/botDetection.js with detectBot() and installBotDetection()
STEP 2: In AppLayout useEffect: call installBotDetection(); disable contextmenu
STEP 3: Add .protected-output { user-select: none } to global CSS
STEP 4: Create components/IPFooter.jsx with legal notices
STEP 5: Add IPFooter to AppLayout/main layout
STEP 6: Create public/robots.txt with Disallow: /api/ and Disallow: /functions/
STEP 7: Replace all "Simulated Demo Environment" banners with professional DemoDisclaimer

Paste this into ${productName}'s Base44 project chat:
"Please install the Self-Protection package for ${productName}. (1) Add right-click protection with polite notice '${productName} is proprietary VEU AI Studio technology.', (2) Add user-select:none CSS class 'protected-output' to all generated content, (3) Add IP notice footer on all pages with copyright 2026 VEU AI Studio and patent pending, (4) Replace any 'Simulated Demo Environment' or 'Demo Mode' banners with: 'This is a controlled demonstration environment. Content is illustrative. Contact us for production access.'"`;
}

export default function CapabilityTransfer() {
  const navigate = useNavigate();
  const [selected, setSelected] = useState(null);
  const [targetUrl, setTargetUrl] = useState('');
  const [generating, setGenerating] = useState(false);
  const [generatedSprint, setGeneratedSprint] = useState(null);

  const generate = async () => {
    if (!selected || !targetUrl.trim()) return;
    setGenerating(true);
    setGeneratedSprint(null);
    // Simulate AI generation (sprint is template-based)
    await new Promise(r => setTimeout(r, 800));
    const sprint = buildConsolidatedSprint(selected, targetUrl.trim());
    setGeneratedSprint(sprint);
    setGenerating(false);
  };

  return (
    <div className="p-8 lg:p-10 max-w-4xl space-y-6">
      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}>
        <h1 className="text-3xl font-bold tracking-tight text-foreground flex items-center gap-2">
          <Package className="h-7 w-7 text-primary" /> Capability Transfer
        </h1>
        <p className="text-sm text-muted-foreground mt-1">
          Install FlowAI governance capabilities into any Base44 product with a single consolidated sprint.
        </p>
      </motion.div>

      {/* Capability selection */}
      <div className="space-y-3">
        <p className="text-[11px] font-bold text-muted-foreground uppercase tracking-wide">Step 1 — Select Capability</p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {CAPABILITIES.map(cap => {
            const Icon = cap.icon;
            const isSelected = selected === cap.id;
            return (
              <div
                key={cap.id}
                onClick={() => { setSelected(cap.id); setGeneratedSprint(null); }}
                className={`rounded-xl border p-5 cursor-pointer transition-all space-y-3 ${isSelected ? cap.color + ' ring-1' : 'border-border bg-card hover:border-primary/30'}`}
              >
                <div className="flex items-center gap-2">
                  <Icon className={`h-4 w-4 ${isSelected ? '' : 'text-muted-foreground'}`} />
                  <span className="text-sm font-bold">{cap.label}</span>
                  {isSelected && <span className="ml-auto text-[10px] font-bold bg-primary/20 text-primary px-2 py-0.5 rounded-full">SELECTED</span>}
                </div>
                <p className="text-[11px] text-muted-foreground">{cap.desc}</p>
                <ul className="space-y-1">
                  {cap.components.map(c => (
                    <li key={c} className="text-[10px] text-muted-foreground flex items-center gap-1.5">
                      <span className="h-1 w-1 rounded-full bg-muted-foreground/50 shrink-0" /> {c}
                    </li>
                  ))}
                </ul>
                <div className="flex gap-2 flex-wrap pt-1">
                  <button
                    onClick={e => { e.stopPropagation(); navigate(cap.detailPath); }}
                    className="text-[10px] text-primary hover:text-primary/80 underline underline-offset-2"
                  >
                    View Package →
                  </button>
                  <button
                    onClick={e => { e.stopPropagation(); navigate(cap.installPath); }}
                    className="text-[10px] text-muted-foreground hover:text-foreground underline underline-offset-2"
                  >
                    View All Product Sprints →
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Target URL */}
      <div className="space-y-3">
        <p className="text-[11px] font-bold text-muted-foreground uppercase tracking-wide">Step 2 — Target Product URL</p>
        <div className="flex gap-2">
          <Input
            value={targetUrl}
            onChange={e => setTargetUrl(e.target.value)}
            placeholder="https://saigedemo.com"
            className="h-9 text-sm flex-1"
          />
          <Button onClick={generate} disabled={!selected || !targetUrl.trim() || generating} className="gap-1.5 shrink-0">
            {generating ? <Loader2 className="h-4 w-4 animate-spin" /> : <Zap className="h-4 w-4" />}
            Generate Sprint
          </Button>
        </div>
      </div>

      {/* Generated sprint */}
      <AnimatePresence>
        {generatedSprint && (
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            className="rounded-xl border border-emerald-500/30 bg-emerald-500/5 p-5 space-y-3"
          >
            <div className="flex items-center justify-between gap-3 flex-wrap">
              <p className="text-sm font-bold text-emerald-400">Sprint Generated</p>
              <CopyBtn text={generatedSprint} />
            </div>
            <p className="text-xs text-muted-foreground">
              Copy this sprint and paste it into the target product's Base44 project. All components will be installed in a single operation.
            </p>
            <div className="rounded-lg bg-background border border-border p-4">
              <pre className="text-[11px] text-foreground whitespace-pre-wrap font-mono leading-relaxed overflow-x-auto max-h-64 overflow-y-auto">
                {generatedSprint}
              </pre>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}