// ─── SELF-RENEWAL INSTALL PAGE — all 5 VEU AI Studio products ───────────────
import { useState } from 'react';
import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { RefreshCw, Copy, Check, ChevronDown, ChevronUp } from 'lucide-react';

function CopyBtn({ text }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      onClick={() => { navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 2000); }}
      className="flex items-center gap-1 text-[10px] border border-border rounded px-2 py-1 text-muted-foreground hover:text-foreground transition-all shrink-0"
    >
      {copied ? <><Check className="h-3 w-3 text-emerald-400" /> Copied</> : <><Copy className="h-3 w-3" /> Copy Sprint</>}
    </button>
  );
}

const PRODUCTS = [
  {
    name: 'SAIGE',
    url: 'saigedemo.com',
    email: 'saige@veuaistudio.com',
    entities: ['UserProfile', 'ConversationSession', 'AIAgent'],
    color: 'border-blue-500/30 bg-blue-500/5',
  },
  {
    name: 'PressAI',
    url: 'ourpublishingai.com',
    email: 'pressai@veuaistudio.com',
    entities: ['Article', 'PublicationSettings', 'ContentDraft'],
    color: 'border-purple-500/30 bg-purple-500/5',
  },
  {
    name: 'RelTwin',
    url: 'reltwin.com',
    email: 'reltwin@veuaistudio.com',
    entities: ['RelationshipProfile', 'TwinSession', 'InsightRecord'],
    color: 'border-emerald-500/30 bg-emerald-500/5',
  },
  {
    name: 'ReachSMS',
    url: 'ourcommunitiesai.com',
    email: 'reachsms@veuaistudio.com',
    entities: ['Campaign', 'Recipient', 'MessageLog'],
    color: 'border-amber-500/30 bg-amber-500/5',
  },
  {
    name: 'MyBirthSafe',
    url: 'safe-path.base44.app',
    email: 'mybirthsafe@veuaistudio.com',
    entities: ['BirthPlan', 'UserProfile', 'SafetyAlert'],
    color: 'border-red-500/30 bg-red-500/5',
  },
];

function buildSprint(product) {
  return `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SELF-RENEWAL INSTALLATION SPRINT — ${product.name}
Target: ${product.url}
Generated by: FlowAI v0.1 — VEU AI Studio
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

COMPONENT 1 — SELF-TEST ENGINE
Sprint Title: Install Self-Test Engine in ${product.name}
File: functions/selfTest.js (new file)

Create functions/selfTest.js:

import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const results = [];
    const entitiesToTest = ${JSON.stringify(product.entities)};

    for (const entity of entitiesToTest) {
      try {
        await base44.asServiceRole.entities[entity].list(undefined, 1);
        results.push({ check: \`Entity:\${entity}\`, status: 'PASS' });
      } catch {
        results.push({ check: \`Entity:\${entity}\`, status: 'FAIL' });
      }
    }

    const passed = results.filter(r => r.status === 'PASS').length;
    const score = Math.round((passed / results.length) * 100);

    // Log result to FlowAI GovernanceAuditLog
    await base44.asServiceRole.entities.GovernanceAuditLog.create({
      action_type: 'session_started',
      action_detail: \`scheduled_self_test: product=${product.name} score=\${score}% passed=\${passed}/\${results.length}\`,
      user: 'system',
      timestamp: new Date().toISOString(),
    }).catch(() => {});

    return Response.json({ product: '${product.name}', score, results, passed, total: results.length });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});

Verification: Run selfTest function from Dashboard > Functions. Confirm ${product.name} entities are tested and score appears.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

COMPONENT 2 — SELF-HEAL MODULE
Sprint Title: Install Self-Heal in ${product.name}
File: functions/selfHeal.js (new file)

import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const cutoff = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
    const healActions = [];

    // Clear stale sessions for ${product.name}
    // Add product-specific healing logic here

    await base44.asServiceRole.entities.GovernanceAuditLog.create({
      action_type: 'fix_applied',
      action_detail: \`self_heal: ${product.name} — \${healActions.length} actions\`,
      user: 'system',
      timestamp: new Date().toISOString(),
    }).catch(() => {});

    return Response.json({ product: '${product.name}', healed: healActions.length });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

COMPONENT 3 — SELF-MONITOR WIDGET
Sprint Title: Add Self-Monitor Widget to ${product.name} Dashboard
File: components/dashboard/SelfMonitorWidget.jsx (new file)
Location: Add to main ${product.name} Dashboard page

Create components/dashboard/SelfMonitorWidget.jsx:
(Use standard SelfMonitorWidget implementation from Component 3 documentation)

Add to ${product.name} Dashboard page import and render:
import SelfMonitorWidget from '@/components/dashboard/SelfMonitorWidget';
// Add <SelfMonitorWidget /> to dashboard grid

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

COMPONENT 4 — GOVERNANCE HOOK
Sprint Title: Install FlowAI Governance Hook in ${product.name}
File: functions/governanceHook.js (new file)

import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const body = await req.json();
    const { event_type, detail, severity } = body;

    await base44.asServiceRole.entities.GovernanceAuditLog.create({
      action_type: 'clearance_decision_issued',
      action_detail: \`governance_hook: [${product.name}] [\${severity || 'INFO'}] \${event_type}: \${detail}\`,
      user: '${product.email}',
      product_url: 'https://${product.url}',
      timestamp: new Date().toISOString(),
    }).catch(() => {});

    return Response.json({ product: '${product.name}', logged: true });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});

Contact: ${product.email}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`;
}

function ProductSprintCard({ product, index }) {
  const [expanded, setExpanded] = useState(false);
  const sprint = buildSprint(product);

  return (
    <motion.div
      initial={{ opacity: 0, y: 6 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.05 }}
      className={`rounded-xl border p-5 space-y-3 ${product.color}`}
    >
      <div className="flex items-center justify-between gap-3 flex-wrap">
        <div>
          <p className="text-sm font-bold text-foreground">{product.name}</p>
          <p className="text-[11px] text-muted-foreground">{product.url} · {product.email}</p>
        </div>
        <div className="flex gap-2 items-center">
          <CopyBtn text={sprint} />
          <button onClick={() => setExpanded(v => !v)} className="text-muted-foreground hover:text-foreground">
            {expanded ? <ChevronUp className="h-3.5 w-3.5" /> : <ChevronDown className="h-3.5 w-3.5" />}
          </button>
        </div>
      </div>
      <div className="flex gap-1.5 flex-wrap">
        {product.entities.map(e => (
          <span key={e} className="text-[9px] px-1.5 py-0.5 rounded bg-background border border-border text-muted-foreground font-mono">{e}</span>
        ))}
      </div>
      {expanded && (
        <div className="rounded-lg bg-background border border-border p-3 overflow-hidden">
          <pre className="text-[10px] text-foreground/80 whitespace-pre-wrap font-mono leading-relaxed overflow-x-auto max-h-64 overflow-y-auto">
            {sprint}
          </pre>
        </div>
      )}
    </motion.div>
  );
}

export default function CapabilityInstallSelfRenewal() {
  const navigate = useNavigate();

  return (
    <div className="p-8 lg:p-10 max-w-4xl space-y-6">
      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}>
        <div className="flex items-center gap-3 flex-wrap">
          <button onClick={() => navigate('/capability-packages/self-renewal')} className="text-xs text-muted-foreground hover:text-foreground">← Self-Renewal Package</button>
          <span className="text-border">/</span>
          <span className="text-xs text-foreground font-semibold">Install — All Products</span>
        </div>
        <h1 className="text-3xl font-bold tracking-tight text-foreground flex items-center gap-2 mt-3">
          <RefreshCw className="h-7 w-7 text-primary" /> Self-Renewal Install Sprints
        </h1>
        <p className="text-sm text-muted-foreground mt-1">
          Product-specific self-renewal installation sprints for all five VEU AI Studio products. Copy and paste each into the target product's Base44 project.
        </p>
      </motion.div>

      <div className="rounded-xl border border-primary/20 bg-primary/5 p-4">
        <p className="text-xs text-muted-foreground">
          Each sprint is product-specific — references the product by name, tests the correct entities, and installs a Governance Hook pointing to FlowAI's audit log.
          Paste the full sprint into the Base44 product project's chat interface.
        </p>
      </div>

      <div className="space-y-4">
        {PRODUCTS.map((product, i) => (
          <ProductSprintCard key={product.name} product={product} index={i} />
        ))}
      </div>
    </div>
  );
}