// ─── SELF-PROTECTION INSTALL PAGE — all 5 VEU AI Studio products ─────────────
import { useState } from 'react';
import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { Shield, Copy, Check, ChevronDown, ChevronUp } from 'lucide-react';

function CopyBtn({ text }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      onClick={() => { navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 2000); }}
      className="flex items-center gap-1 text-[10px] border border-border rounded px-2 py-1 text-muted-foreground hover:text-foreground transition-all shrink-0"
    >
      {copied ? <><Check className="h-3 w-3 text-emerald-400" /> Copied</> : <><Copy className="h-3 w-3" /> Copy Sprint</>}
    </button>
  );
}

const PRODUCTS = [
  { name: 'SAIGE',       url: 'saigedemo.com',              email: 'saige@veuaistudio.com',       color: 'border-blue-500/30 bg-blue-500/5' },
  { name: 'PressAI',     url: 'ourpublishingai.com',         email: 'pressai@veuaistudio.com',     color: 'border-purple-500/30 bg-purple-500/5' },
  { name: 'RelTwin',     url: 'reltwin.com',                 email: 'reltwin@veuaistudio.com',     color: 'border-emerald-500/30 bg-emerald-500/5' },
  { name: 'ReachSMS',    url: 'ourcommunitiesai.com',        email: 'reachsms@veuaistudio.com',    color: 'border-amber-500/30 bg-amber-500/5' },
  { name: 'MyBirthSafe', url: 'safe-path.base44.app',        email: 'mybirthsafe@veuaistudio.com', color: 'border-red-500/30 bg-red-500/5' },
];

function buildSprint(product) {
  return `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SELF-PROTECTION INSTALLATION SPRINT — ${product.name}
Target: ${product.url}
Generated by: FlowAI v0.1 — VEU AI Studio
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

COMPONENT 1 — ANTI-CRAWLING PROTECTION
Sprint Title: Install Anti-Crawling in ${product.name}
File: lib/botDetection.js (new file) + AppLayout

Create lib/botDetection.js for ${product.name}:

export function detectBot(userAgent = '') {
  const ua = userAgent.toLowerCase();
  const headlessSignals = ['headlesschrome', 'phantomjs', 'selenium', 'webdriver', 'puppeteer', 'playwright'];
  if (headlessSignals.some(sig => ua.includes(sig))) return 'headless_browser';
  if (!userAgent || ua === '') return 'missing_useragent';
  return null;
}

export function installBotDetection(onDetect) {
  const bot = detectBot(navigator.userAgent);
  if (bot) onDetect('${product.name}:' + bot);

  let rapidClicks = 0, lastClick = 0;
  document.addEventListener('click', () => {
    const now = Date.now();
    if (now - lastClick < 50) rapidClicks++;
    else rapidClicks = 0;
    lastClick = now;
    if (rapidClicks > 10) onDetect('${product.name}:rapid_automated_clicks');
  });
}

In AppLayout, add:
import { installBotDetection } from '@/lib/botDetection';
useEffect(() => {
  installBotDetection((signal) => {
    console.warn('[${product.name}] Bot signal:', signal);
    // Optionally log to GovernanceAuditLog via governanceHook
  });
}, []);

Also create public/robots.txt:
User-agent: *
Disallow: /api/
Disallow: /functions/
Crawl-delay: 10
# ${product.name} — VEU AI Studio — Unauthorized scraping prohibited

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

COMPONENT 2 — CONTENT PROTECTION
Sprint Title: Install Content Protection in ${product.name}

In ${product.name}'s AppLayout or root component:

useEffect(() => {
  document.addEventListener('contextmenu', (e) => {
    e.preventDefault();
    const el = document.createElement('div');
    el.style.cssText = 'position:fixed;bottom:80px;left:50%;transform:translateX(-50%);background:#0e1521;border:1px solid rgba(59,130,246,0.4);color:#94a3b8;font-size:12px;padding:10px 16px;border-radius:8px;z-index:99999;pointer-events:none;';
    el.textContent = '${product.name} is proprietary VEU AI Studio technology.';
    document.body.appendChild(el);
    setTimeout(() => el.remove(), 2500);
    return false;
  });
}, []);

Add to global CSS:
.protected-output { user-select: none !important; -webkit-user-select: none !important; }

Wrap all AI-generated output in <div className="protected-output relative">.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

COMPONENT 3 — IP NOTICE FOOTER
Sprint Title: Add IP Notice Footer to ${product.name}

Create components/IPFooter.jsx in ${product.name}:

export default function IPFooter() {
  return (
    <footer style={{borderTop:'1px solid #1e2d40',background:'rgba(14,21,33,0.3)',padding:'16px 24px',marginTop:'auto',textAlign:'center'}}>
      <p style={{fontSize:'10px',color:'#64748b',marginBottom:'4px'}}>
        ${product.name} is proprietary technology of VEU AI Studio. Unauthorized access, scraping, reverse engineering, or redistribution is prohibited.
      </p>
      <p style={{fontSize:'10px',color:'#64748b'}}>
        © 2026 VEU AI Studio. All rights reserved. Patent pending.
      </p>
    </footer>
  );
}

Add <IPFooter /> to the bottom of ${product.name}'s main layout.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

COMPONENT 4 — DEMO ENVIRONMENT DISCLAIMER
Sprint Title: Replace Demo Notice in ${product.name}

Search ${product.name} codebase for all occurrences of:
- "Simulated Demo Environment"
- "Demo Mode"
- "This is a demo"

Replace each with this professional notice:

<div style={{width:'100%',background:'rgba(59,130,246,0.05)',borderBottom:'1px solid rgba(59,130,246,0.2)',padding:'8px 16px',textAlign:'center'}}>
  <p style={{fontSize:'11px',color:'#64748b'}}>
    This is a controlled demonstration environment. Content is illustrative.{' '}
    <a href="mailto:${product.email}" style={{color:'#3b82f6',fontWeight:600}}>
      Contact us for production access
    </a>
  </p>
</div>

Contact: ${product.email}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`;
}

function ProductSprintCard({ product, index }) {
  const [expanded, setExpanded] = useState(false);
  const sprint = buildSprint(product);

  return (
    <motion.div
      initial={{ opacity: 0, y: 6 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.05 }}
      className={`rounded-xl border p-5 space-y-3 ${product.color}`}
    >
      <div className="flex items-center justify-between gap-3 flex-wrap">
        <div>
          <p className="text-sm font-bold text-foreground">{product.name}</p>
          <p className="text-[11px] text-muted-foreground">{product.url} · {product.email}</p>
        </div>
        <div className="flex gap-2 items-center">
          <CopyBtn text={sprint} />
          <button onClick={() => setExpanded(v => !v)} className="text-muted-foreground hover:text-foreground">
            {expanded ? <ChevronUp className="h-3.5 w-3.5" /> : <ChevronDown className="h-3.5 w-3.5" />}
          </button>
        </div>
      </div>
      {expanded && (
        <div className="rounded-lg bg-background border border-border p-3 overflow-hidden">
          <pre className="text-[10px] text-foreground/80 whitespace-pre-wrap font-mono leading-relaxed overflow-x-auto max-h-64 overflow-y-auto">
            {sprint}
          </pre>
        </div>
      )}
    </motion.div>
  );
}

export default function CapabilityInstallSelfProtection() {
  const navigate = useNavigate();

  return (
    <div className="p-8 lg:p-10 max-w-4xl space-y-6">
      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}>
        <div className="flex items-center gap-3 flex-wrap">
          <button onClick={() => navigate('/capability-packages/self-protection')} className="text-xs text-muted-foreground hover:text-foreground">← Self-Protection Package</button>
          <span className="text-border">/</span>
          <span className="text-xs text-foreground font-semibold">Install — All Products</span>
        </div>
        <h1 className="text-3xl font-bold tracking-tight text-foreground flex items-center gap-2 mt-3">
          <Shield className="h-7 w-7 text-primary" /> Self-Protection Install Sprints
        </h1>
        <p className="text-sm text-muted-foreground mt-1">
          Product-specific self-protection installation sprints for all five VEU AI Studio products.
        </p>
      </motion.div>

      <div className="space-y-4">
        {PRODUCTS.map((product, i) => (
          <ProductSprintCard key={product.name} product={product} index={i} />
        ))}
      </div>
    </div>
  );
}