export const MIN_SOURCE_MAP_CONFIDENCE = 0.65;

export const SOURCE_MAPPING_STATUSES = Object.freeze({
  PLATFORM_BOUNDARY_BLOCKED: 'PLATFORM_BOUNDARY_BLOCKED',
  HUMAN_REVIEW_REQUIRED: 'HUMAN_REVIEW_REQUIRED',
  SOURCE_MAP_INCOMPLETE: 'source_map_incomplete',
  ACTIONABLE: 'actionable',
});
