-- 0012_test_tenant.sql
-- Provisions the system-only `_test` tenant required by the FlowAI
-- self-adversarial test plan Rev-1 (docs/specs/
-- FLOWAI_SELF_ADVERSARIAL_TEST_PLAN.md §9 LD-2 + §11.8).
--
-- Spec/canonical context:
--   - PRODUCT_SCOPES enum in src/lib/agents/BaseAgent.js + the
--     VALID_PRODUCT_SCOPES set in src/lib/agents/MessageSchema.js
--     have both been extended to accept `_test` as a valid scope.
--   - Test rows authored against this tenant must be cleaned up
--     between runs via scripts/cleanup-test-tenant.mjs.
--   - This migration is idempotent — re-running is safe and has no
--     effect once the `_test` row exists.
--
-- Identity convention:
--   - `clerk_org_id = '_test'` is the durable cross-environment
--     handle. The underlying uuid `id` is generated by Postgres on
--     first apply; tests resolve to the uuid via the clerk_org_id
--     lookup so they remain reproducible across local / CI / prd.
--   - `slug = '_test'` is the human-readable alias surfaced in UI
--     and logs.
--   - `metadata.is_system_test_tenant = true` marks the row for
--     downstream tooling that needs to distinguish system rows from
--     real tenants without parsing the slug. The full metadata
--     payload also pins `metadata.product_scope = '_test'` so a
--     future product_scope column can be backfilled from metadata
--     without re-touching this row.
--
-- RLS interaction:
--   - The organizations RLS policies from migration 0011 §4.1 are
--     unchanged. Members see their own org; non-members see nothing;
--     INSERT/DELETE remain service_role-only. The `_test` row is
--     never JWT-authenticated; it's reachable only via the
--     service_role connection that the test harness and the
--     cleanup helper use.
--
-- Roll-out dependency:
--   - This migration CAN be applied today (no new schema, just an
--     INSERT into an existing table). It does NOT depend on W1's
--     SUPABASE_JWT_SECRET wiring; that wiring is for RLS-enforced
--     reads from authenticated clients, not for service_role
--     writes via the migration runner.

begin;

-- ════════════════════════════════════════════════════════════════════
-- 1. INSERT the `_test` organization row (idempotent)
-- ════════════════════════════════════════════════════════════════════

insert into public.organizations (
  clerk_org_id,
  name,
  slug,
  plan,
  metadata
)
values (
  '_test',
  'FlowAI Test Tenant',
  '_test',
  'system',
  jsonb_build_object(
    'is_system_test_tenant', true,
    'product_scope',         '_test',
    'created_by_migration',  '0012_test_tenant.sql',
    'never_bind_to_customer', true
  )
)
on conflict (clerk_org_id) do nothing;

-- ════════════════════════════════════════════════════════════════════
-- 2. Verify post-condition (commented; rerun to validate manually)
-- ════════════════════════════════════════════════════════════════════
-- select id, clerk_org_id, slug, name, plan, metadata
-- from public.organizations
-- where clerk_org_id = '_test';

commit;
